# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
Endpoints to manage user's memberships. Memberships are used to connect the user to merchant accounts and to grant them access to the merchant's resources via roles.
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import (
    Attributes,
    Invite,
    Membership,
    MembershipResource,
    MembershipStatus,
    Metadata,
    Problem,
    ResourceType,
)
from ..types import MembershipStatusInput, ResourceTypeInput
import datetime
import httpx
import typing
import pydantic
import typing_extensions


class ListMembershipsParamsResourceParentTypeInput(typing_extensions.TypedDict, total=False):
    """
    ListMembershipsParamsResourceParentType is a schema definition.
    """

    pass


class ListMemberships200Response(pydantic.BaseModel):
    """
    ListMemberships200Response is a schema definition.
    """

    items: list[Membership]

    total_count: int


class MembershipsResource(Resource):
    """API resource for the Memberships endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def list(
        self,
        *,
        offset: typing.Union[int, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        kind: typing.Union[ResourceTypeInput, NotGivenType] = NOT_GIVEN,
        status: typing.Union[MembershipStatusInput, NotGivenType] = NOT_GIVEN,
        resource_type: typing.Union[ResourceTypeInput, NotGivenType] = NOT_GIVEN,
        resource_attributes_sandbox: typing.Union[bool, NotGivenType] = NOT_GIVEN,
        resource_name: typing.Union[str, NotGivenType] = NOT_GIVEN,
        resource_parent_id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        resource_parent_type: typing.Union[
            ListMembershipsParamsResourceParentTypeInput, NotGivenType
        ] = NOT_GIVEN,
        roles: typing.Union[typing.Sequence[str], NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListMemberships200Response:
        """
        List memberships

        List memberships of the current user.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(offset, NotGivenType) and offset is not None:
            query_data["offset"] = offset
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(kind, NotGivenType) and kind is not None:
            query_data["kind"] = kind
        if not isinstance(status, NotGivenType) and status is not None:
            query_data["status"] = status
        if not isinstance(resource_type, NotGivenType) and resource_type is not None:
            query_data["resource.type"] = resource_type
        if (
            not isinstance(resource_attributes_sandbox, NotGivenType)
            and resource_attributes_sandbox is not None
        ):
            query_data["resource.attributes.sandbox"] = resource_attributes_sandbox
        if not isinstance(resource_name, NotGivenType) and resource_name is not None:
            query_data["resource.name"] = resource_name
        if not isinstance(resource_parent_id, NotGivenType) and resource_parent_id is not None:
            query_data["resource.parent.id"] = resource_parent_id
        if not isinstance(resource_parent_type, NotGivenType) and resource_parent_type is not None:
            query_data["resource.parent.type"] = resource_parent_type
        if not isinstance(roles, NotGivenType) and roles is not None:
            query_data["roles"] = list(roles)

        resp = self._client.get(
            f"/v0.1/memberships",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListMemberships200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Invalid query parameter combination.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncMembershipsResource(AsyncResource):
    """Async API resource for the Memberships endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def list(
        self,
        *,
        offset: typing.Union[int, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        kind: typing.Union[ResourceTypeInput, NotGivenType] = NOT_GIVEN,
        status: typing.Union[MembershipStatusInput, NotGivenType] = NOT_GIVEN,
        resource_type: typing.Union[ResourceTypeInput, NotGivenType] = NOT_GIVEN,
        resource_attributes_sandbox: typing.Union[bool, NotGivenType] = NOT_GIVEN,
        resource_name: typing.Union[str, NotGivenType] = NOT_GIVEN,
        resource_parent_id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        resource_parent_type: typing.Union[
            ListMembershipsParamsResourceParentTypeInput, NotGivenType
        ] = NOT_GIVEN,
        roles: typing.Union[typing.Sequence[str], NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListMemberships200Response:
        """
        List memberships

        List memberships of the current user.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(offset, NotGivenType) and offset is not None:
            query_data["offset"] = offset
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(kind, NotGivenType) and kind is not None:
            query_data["kind"] = kind
        if not isinstance(status, NotGivenType) and status is not None:
            query_data["status"] = status
        if not isinstance(resource_type, NotGivenType) and resource_type is not None:
            query_data["resource.type"] = resource_type
        if (
            not isinstance(resource_attributes_sandbox, NotGivenType)
            and resource_attributes_sandbox is not None
        ):
            query_data["resource.attributes.sandbox"] = resource_attributes_sandbox
        if not isinstance(resource_name, NotGivenType) and resource_name is not None:
            query_data["resource.name"] = resource_name
        if not isinstance(resource_parent_id, NotGivenType) and resource_parent_id is not None:
            query_data["resource.parent.id"] = resource_parent_id
        if not isinstance(resource_parent_type, NotGivenType) and resource_parent_type is not None:
            query_data["resource.parent.type"] = resource_parent_type
        if not isinstance(roles, NotGivenType) and roles is not None:
            query_data["roles"] = list(roles)

        resp = await self._client.get(
            f"/v0.1/memberships",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListMemberships200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Invalid query parameter combination.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
