# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
The Payouts model will allow you to track funds you’ve received from SumUp.

You can receive a detailed payouts list with information like dates, fees, references and statuses, using the `List payouts` endpoint.
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import Error, ErrorExtended, FinancialPayout, FinancialPayouts, Problem
import datetime
import httpx
import typing
import pydantic
import typing_extensions

ListPayoutsV1ParamsFormatInput = typing.Union[typing.Literal["csv", "json"], str]

ListPayoutsV1ParamsOrderInput = typing.Union[typing.Literal["asc", "desc"], str]


class PayoutsResource(Resource):
    """API resource for the Payouts endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def list(
        self,
        merchant_code: str,
        *,
        start_date: datetime.date,
        end_date: datetime.date,
        format: typing.Union[ListPayoutsV1ParamsFormatInput, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        order: typing.Union[ListPayoutsV1ParamsOrderInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> FinancialPayouts:
        """
        List payouts

        Lists payout and payout-deduction records for the specified merchant account within the requested date range.

        The response can include:
        - regular payouts (`type = PAYOUT`)
        - deduction records for refunds, chargebacks, direct debit returns, or balance adjustments

        Results are sorted by payout date in the requested `order`.
        """
        query_data: dict[str, typing.Any] = {}
        query_data["start_date"] = start_date
        query_data["end_date"] = end_date
        if not isinstance(format, NotGivenType) and format is not None:
            query_data["format"] = format
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(order, NotGivenType) and order is not None:
            query_data["order"] = order

        resp = self._client.get(
            f"/v1.0/merchants/{merchant_code}/payouts",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(FinancialPayouts).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncPayoutsResource(AsyncResource):
    """Async API resource for the Payouts endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def list(
        self,
        merchant_code: str,
        *,
        start_date: datetime.date,
        end_date: datetime.date,
        format: typing.Union[ListPayoutsV1ParamsFormatInput, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        order: typing.Union[ListPayoutsV1ParamsOrderInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> FinancialPayouts:
        """
        List payouts

        Lists payout and payout-deduction records for the specified merchant account within the requested date range.

        The response can include:
        - regular payouts (`type = PAYOUT`)
        - deduction records for refunds, chargebacks, direct debit returns, or balance adjustments

        Results are sorted by payout date in the requested `order`.
        """
        query_data: dict[str, typing.Any] = {}
        query_data["start_date"] = start_date
        query_data["end_date"] = end_date
        if not isinstance(format, NotGivenType) and format is not None:
            query_data["format"] = format
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(order, NotGivenType) and order is not None:
            query_data["order"] = order

        resp = await self._client.get(
            f"/v1.0/merchants/{merchant_code}/payouts",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(FinancialPayouts).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
