# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
Endpoints for managing merchant sub-accounts (operators).
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import Operator, Permissions, Problem
from ..types import OperatorInput, PermissionsInput, ProblemInput
import datetime
import httpx
import typing
import pydantic
import typing_extensions


class CreateSubAccountBodyPermissionsInput(typing_extensions.TypedDict, total=False):
    """
    CreateSubAccountBodyPermissions is a schema definition.
    """

    create_moto_payments: typing_extensions.NotRequired[bool]
    create_referral: typing_extensions.NotRequired[bool]
    full_transaction_history_view: typing_extensions.NotRequired[bool]
    refund_transactions: typing_extensions.NotRequired[bool]


class CreateSubAccountBodyInput(typing_extensions.TypedDict, total=False):
    """
    CreateSubAccountBody is a schema definition.
    """

    password: typing_extensions.Required[
        typing_extensions.Annotated[str, typing_extensions.Doc("Min length: 8")]
    ]
    username: typing_extensions.Required[
        typing_extensions.Annotated[str, typing_extensions.Doc("Format: email")]
    ]
    nickname: typing_extensions.NotRequired[str]
    permissions: typing_extensions.NotRequired[CreateSubAccountBodyPermissionsInput]


class UpdateSubAccountBodyPermissionsInput(typing_extensions.TypedDict, total=False):
    """
    UpdateSubAccountBodyPermissions is a schema definition.
    """

    create_moto_payments: typing_extensions.NotRequired[bool]
    create_referral: typing_extensions.NotRequired[bool]
    full_transaction_history_view: typing_extensions.NotRequired[bool]
    refund_transactions: typing_extensions.NotRequired[bool]


class UpdateSubAccountBodyInput(typing_extensions.TypedDict, total=False):
    """
    UpdateSubAccountBody is a schema definition.
    """

    disabled: typing_extensions.NotRequired[bool]
    nickname: typing_extensions.NotRequired[str]
    password: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, typing_extensions.Doc("Min length: 8")]
    ]
    permissions: typing_extensions.NotRequired[UpdateSubAccountBodyPermissionsInput]
    username: typing_extensions.NotRequired[
        typing_extensions.Annotated[str, typing_extensions.Doc("Format: email\nMax length: 256")]
    ]


ListSubAccounts200Response = list[Operator]
ListSubAccounts200ResponseInput = typing.Sequence[OperatorInput]
"""
ListSubAccounts200Response is a schema definition.
"""


class SubaccountsResource(Resource):
    """API resource for the Subaccounts endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to list users in your merchant account please use [List members](https://developer.sumup.com/api/members/list) instead."
    )
    def list_sub_accounts(
        self,
        *,
        query: typing.Union[str, NotGivenType] = NOT_GIVEN,
        include_primary: typing.Union[bool, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListSubAccounts200Response:
        """
        List operators

        Returns list of operators for currently authorized user's merchant.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(query, NotGivenType) and query is not None:
            query_data["query"] = query
        if not isinstance(include_primary, NotGivenType) and include_primary is not None:
            query_data["include_primary"] = include_primary

        resp = self._client.get(
            f"/v0.1/me/accounts",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListSubAccounts200Response).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to create a user in your merchant account please use [Create member](https://developer.sumup.com/api/members/create) instead."
    )
    def create_sub_account(
        self,
        *,
        username: str,
        password: str,
        nickname: typing.Union[str, NotGivenType] = NOT_GIVEN,
        permissions: typing.Union[CreateSubAccountBodyPermissionsInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Operator:
        """
        Create an operator

        Creates new operator for currently authorized users' merchant.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["username"] = username
        body_data["password"] = password
        if not isinstance(nickname, NotGivenType):
            body_data["nickname"] = nickname
        if not isinstance(permissions, NotGivenType):
            body_data["permissions"] = permissions

        resp = self._client.post(
            f"/v0.1/me/accounts",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Operator).validate_python(resp.json())
        elif resp.status_code == 403:
            raise APIError(
                "Operator creation was forbidden.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to get a user that's a member of your merchant account please use [Get member](https://developer.sumup.com/api/members/get) instead."
    )
    def compat_get_operator(
        self, operator_id: int, headers: typing.Optional[HeaderTypes] = None
    ) -> Operator:
        """
        Retrieve an operator

        Returns specific operator.
        """
        resp = self._client.get(
            f"/v0.1/me/accounts/{operator_id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Operator).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to update a user that's a member of your merchant account please use [Update member](https://developer.sumup.com/api/members/update) instead."
    )
    def update_sub_account(
        self,
        operator_id: int,
        *,
        password: typing.Union[str, NotGivenType] = NOT_GIVEN,
        username: typing.Union[str, NotGivenType] = NOT_GIVEN,
        disabled: typing.Union[bool, NotGivenType] = NOT_GIVEN,
        nickname: typing.Union[str, NotGivenType] = NOT_GIVEN,
        permissions: typing.Union[UpdateSubAccountBodyPermissionsInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Operator:
        """
        Update an operator

        Updates operator. If the operator was disabled and their password is updated they will be unblocked.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(password, NotGivenType):
            body_data["password"] = password
        if not isinstance(username, NotGivenType):
            body_data["username"] = username
        if not isinstance(disabled, NotGivenType):
            body_data["disabled"] = disabled
        if not isinstance(nickname, NotGivenType):
            body_data["nickname"] = nickname
        if not isinstance(permissions, NotGivenType):
            body_data["permissions"] = permissions

        resp = self._client.put(
            f"/v0.1/me/accounts/{operator_id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Operator).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Invalid Operators' email or password was already used.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncSubaccountsResource(AsyncResource):
    """Async API resource for the Subaccounts endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to list users in your merchant account please use [List members](https://developer.sumup.com/api/members/list) instead."
    )
    async def list_sub_accounts(
        self,
        *,
        query: typing.Union[str, NotGivenType] = NOT_GIVEN,
        include_primary: typing.Union[bool, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListSubAccounts200Response:
        """
        List operators

        Returns list of operators for currently authorized user's merchant.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(query, NotGivenType) and query is not None:
            query_data["query"] = query
        if not isinstance(include_primary, NotGivenType) and include_primary is not None:
            query_data["include_primary"] = include_primary

        resp = await self._client.get(
            f"/v0.1/me/accounts",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListSubAccounts200Response).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to create a user in your merchant account please use [Create member](https://developer.sumup.com/api/members/create) instead."
    )
    async def create_sub_account(
        self,
        *,
        username: str,
        password: str,
        nickname: typing.Union[str, NotGivenType] = NOT_GIVEN,
        permissions: typing.Union[CreateSubAccountBodyPermissionsInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Operator:
        """
        Create an operator

        Creates new operator for currently authorized users' merchant.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["username"] = username
        body_data["password"] = password
        if not isinstance(nickname, NotGivenType):
            body_data["nickname"] = nickname
        if not isinstance(permissions, NotGivenType):
            body_data["permissions"] = permissions

        resp = await self._client.post(
            f"/v0.1/me/accounts",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Operator).validate_python(resp.json())
        elif resp.status_code == 403:
            raise APIError(
                "Operator creation was forbidden.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to get a user that's a member of your merchant account please use [Get member](https://developer.sumup.com/api/members/get) instead."
    )
    async def compat_get_operator(
        self, operator_id: int, headers: typing.Optional[HeaderTypes] = None
    ) -> Operator:
        """
        Retrieve an operator

        Returns specific operator.
        """
        resp = await self._client.get(
            f"/v0.1/me/accounts/{operator_id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Operator).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated(
        "Subaccounts API is deprecated, to update a user that's a member of your merchant account please use [Update member](https://developer.sumup.com/api/members/update) instead."
    )
    async def update_sub_account(
        self,
        operator_id: int,
        *,
        password: typing.Union[str, NotGivenType] = NOT_GIVEN,
        username: typing.Union[str, NotGivenType] = NOT_GIVEN,
        disabled: typing.Union[bool, NotGivenType] = NOT_GIVEN,
        nickname: typing.Union[str, NotGivenType] = NOT_GIVEN,
        permissions: typing.Union[UpdateSubAccountBodyPermissionsInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Operator:
        """
        Update an operator

        Updates operator. If the operator was disabled and their password is updated they will be unblocked.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(password, NotGivenType):
            body_data["password"] = password
        if not isinstance(username, NotGivenType):
            body_data["username"] = username
        if not isinstance(disabled, NotGivenType):
            body_data["disabled"] = disabled
        if not isinstance(nickname, NotGivenType):
            body_data["nickname"] = nickname
        if not isinstance(permissions, NotGivenType):
            body_data["permissions"] = permissions

        resp = await self._client.put(
            f"/v0.1/me/accounts/{operator_id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Operator).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Invalid Operators' email or password was already used.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
