# Code generated by `py-sdk-gen`. DO NOT EDIT.
import datetime
import typing
import pydantic


class Permissions(pydantic.BaseModel):
    """
    User permissions
    """

    create_moto_payments: typing.Optional[bool] = None
    """
	Create MOTO payments
	"""

    create_referral: typing.Optional[bool] = None
    """
	Create referral
	"""

    full_transaction_history_view: typing.Optional[bool] = None
    """
	Can view full merchant transaction history
	"""

    refund_transactions: typing.Optional[bool] = None
    """
	Refund transactions
	"""


OperatorAccountType = typing.Literal["normal", "operator"]


class Operator(pydantic.BaseModel):
    """
    Operator account for a merchant.
    """

    account_type: OperatorAccountType

    created_at: datetime.datetime
    """
	The timestamp of when the operator was created.
	"""

    disabled: bool

    id: int
    """
	Format: int32
	"""

    permissions: Permissions
    """
	User permissions
	"""

    updated_at: datetime.datetime
    """
	The timestamp of when the operator was last updated.
	"""

    username: str

    nickname: typing.Optional[str] = None


class CompatError(pydantic.BaseModel):
    """
    Error object for compat API calls.
    """

    error_code: str

    message: str
