# Code generated by `py-sdk-gen`. DO NOT EDIT.
import datetime
import typing
import pydantic


class Permissions(pydantic.BaseModel):
    """
    Permissions assigned to an operator or user.
    """

    admin: bool

    create_moto_payments: bool

    create_referral: bool

    full_transaction_history_view: bool

    refund_transactions: bool


OperatorAccountType = typing.Union[typing.Literal["normal", "operator"], str]


class Operator(pydantic.BaseModel):
    """
    Operator account for a merchant.
    """

    account_type: OperatorAccountType

    created_at: datetime.datetime
    """
	The timestamp of when the operator was created.
	"""

    disabled: bool

    id: int
    """
	Format: int32
	"""

    permissions: Permissions
    """
	Permissions assigned to an operator or user.
	"""

    updated_at: datetime.datetime
    """
	The timestamp of when the operator was last updated.
	"""

    username: str

    nickname: typing.Optional[str] = None


class Problem(pydantic.BaseModel):
    """
            A RFC 9457 problem details object.

    Additional properties specific to the problem type may be present.
    """

    type: str
    """
	A URI reference that identifies the problem type.
	Format: uri
	"""

    detail: typing.Optional[str] = None
    """
	A human-readable explanation specific to this occurrence of the problem.
	"""

    instance: typing.Optional[str] = None
    """
	A URI reference that identifies the specific occurrence of the problem.
	Format: uri
	"""

    status: typing.Optional[int] = None
    """
	The HTTP status code generated by the origin server for this occurrence of the problem.
	"""

    title: typing.Optional[str] = None
    """
	A short, human-readable summary of the problem type.
	"""

    model_config = pydantic.ConfigDict(extra="allow")

    @pydantic.model_validator(mode="before")
    @classmethod
    def _merge_additional_properties(cls, values: typing.Any) -> typing.Any:
        if not isinstance(values, dict):
            return values

        additional = values.get("additional_properties")
        if not isinstance(additional, dict):
            return values

        merged = dict(additional)
        for key, value in values.items():
            if key != "additional_properties":
                merged[key] = value

        return merged

    @property
    def additional_properties(self) -> dict[str, typing.Any]:
        if self.model_extra is None:
            object.__setattr__(self, "__pydantic_extra__", {})
        return typing.cast(dict[str, typing.Any], self.model_extra)

    @additional_properties.setter
    def additional_properties(self, value: dict[str, typing.Any]) -> None:
        object.__setattr__(self, "__pydantic_extra__", dict(value))
