# Code generated by `py-sdk-gen`. DO NOT EDIT.
import datetime
import typing
import pydantic


class Permissions(pydantic.BaseModel):
    """
    Permissions assigned to an operator or user.
    """

    admin: bool

    create_moto_payments: bool

    create_referral: bool

    full_transaction_history_view: bool

    refund_transactions: bool


OperatorAccountType = typing.Literal["normal", "operator"]


class Operator(pydantic.BaseModel):
    """
    Operator account for a merchant.
    """

    account_type: OperatorAccountType

    created_at: datetime.datetime
    """
	The timestamp of when the operator was created.
	"""

    disabled: bool

    id: int
    """
	Format: int32
	"""

    permissions: Permissions
    """
	Permissions assigned to an operator or user.
	"""

    updated_at: datetime.datetime
    """
	The timestamp of when the operator was last updated.
	"""

    username: str

    nickname: typing.Optional[str] = None


class CompatError(pydantic.BaseModel):
    """
    Error object for compat API calls.
    """

    error_code: str

    message: str
