# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
A reader represents a device that accepts payments. You can use the SumUp Solo to accept in-person payments.
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import (
    BadRequest,
    CreateReaderCheckoutError,
    CreateReaderCheckoutRequest,
    CreateReaderCheckoutResponse,
    CreateReaderCheckoutUnprocessableEntity,
    CreateReaderTerminateError,
    CreateReaderTerminateUnprocessableEntity,
    Metadata,
    NotFound,
    Problem,
    Reader,
    ReaderDevice,
    ReaderId,
    ReaderName,
    ReaderPairingCode,
    ReaderStatus,
    StatusResponse,
    Unauthorized,
)
from ..types import (
    BadRequestInput,
    CreateReaderCheckoutErrorInput,
    CreateReaderCheckoutRequestInput,
    CreateReaderCheckoutResponseInput,
    CreateReaderCheckoutUnprocessableEntityInput,
    CreateReaderTerminateErrorInput,
    CreateReaderTerminateUnprocessableEntityInput,
    MetadataInput,
    NotFoundInput,
    ProblemInput,
    ReaderInput,
    ReaderDeviceInput,
    ReaderIdInput,
    ReaderNameInput,
    ReaderPairingCodeInput,
    ReaderStatusInput,
    StatusResponseInput,
    UnauthorizedInput,
)
import datetime
import httpx
import typing
import pydantic
import typing_extensions


class CreateReaderBodyInput(typing_extensions.TypedDict, total=False):
    """
    CreateReaderBody is a schema definition.
    """

    name: typing_extensions.Required[
        typing_extensions.Annotated[
            ReaderNameInput,
            typing_extensions.Doc(
                "Custom human-readable, user-defined name for easier identification of the reader.\nMax length: 500"
            ),
        ]
    ]
    pairing_code: typing_extensions.Required[
        typing_extensions.Annotated[
            ReaderPairingCodeInput,
            typing_extensions.Doc(
                "The pairing code is a 8 or 9 character alphanumeric string that is displayed on a SumUp Device after initiatingthe pairing. It is used to link the physical device to the created pairing.\nMin length: 8\nMax length: 9"
            ),
        ]
    ]
    metadata: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            MetadataInput,
            typing_extensions.Doc(
                "Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, alwayssubmit whole metadata. Maximum of 64 parameters are allowed in the object.\nMax properties: 64"
            ),
        ]
    ]


class UpdateReaderBodyInput(typing_extensions.TypedDict, total=False):
    """
    UpdateReaderBody is a schema definition.
    """

    metadata: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            MetadataInput,
            typing_extensions.Doc(
                "Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, alwayssubmit whole metadata. Maximum of 64 parameters are allowed in the object.\nMax properties: 64"
            ),
        ]
    ]
    name: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            ReaderNameInput,
            typing_extensions.Doc(
                "Custom human-readable, user-defined name for easier identification of the reader.\nMax length: 500"
            ),
        ]
    ]


class CreateReaderCheckoutBodyAadeInput(typing_extensions.TypedDict, total=False):
    """
            Optional object containing data for transactions from ERP integrators in Greece that comply with the AADE1155 protocol.
    When such regulatory/business requirements apply, this object must be provided and contains the data needed tovalidate the transaction with the AADE signature provider.
    """

    provider_id: typing_extensions.Required[
        typing_extensions.Annotated[
            str, typing_extensions.Doc("The identifier of the AADE signature provider.")
        ]
    ]
    signature: typing_extensions.Required[
        typing_extensions.Annotated[
            str, typing_extensions.Doc("The base64 encoded signature of the transaction data.")
        ]
    ]
    signature_data: typing_extensions.Required[
        typing_extensions.Annotated[
            str, typing_extensions.Doc("The string containing the signed transaction data.")
        ]
    ]


CreateReaderCheckoutBodyAffiliateTagsInput = typing.Mapping[str, object]
"""
Additional metadata for the transaction.
It is key-value object that can be associated with the transaction.
"""


class CreateReaderCheckoutBodyAffiliateInput(typing_extensions.TypedDict, total=False):
    """
            Affiliate metadata for the transaction.
    It is a field that allow for integrators to track the source of the transaction.
    """

    app_id: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Application ID of the affiliate.\nIt is a unique identifier for the application and should be set by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page."
            ),
        ]
    ]
    foreign_transaction_id: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Foreign transaction ID of the affiliate.\nIt is a unique identifier for the transaction.\nIt can be used later to fetch the transaction details via the [Transactions API](https://developer.sumup.com/api/transactions/get)."
            ),
        ]
    ]
    key: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Key of the affiliate.\nIt is a unique identifier for the key  and should be generated by the integrator in the [Affiliate Keys](https://developer.sumup.com/affiliate-keys) page."
            ),
        ]
    ]
    tags: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateReaderCheckoutBodyAffiliateTagsInput,
            typing_extensions.Doc(
                "Additional metadata for the transaction.\nIt is key-value object that can be associated with the transaction."
            ),
        ]
    ]


CreateReaderCheckoutBodyCardType = typing.Union[typing.Literal["credit", "debit"], str]
CreateReaderCheckoutBodyCardTypeInput = CreateReaderCheckoutBodyCardType


class CreateReaderCheckoutBodyTotalAmountInput(typing_extensions.TypedDict, total=False):
    """
            Amount structure.

    The amount is represented as an integer value altogether with the currency and the minor unit.

    For example, EUR 1.00 is represented as value 100 with minor unit of 2.
    """

    currency: typing_extensions.Required[
        typing_extensions.Annotated[str, typing_extensions.Doc("Currency ISO 4217 code")]
    ]
    minor_unit: typing_extensions.Required[
        typing_extensions.Annotated[
            int,
            typing_extensions.Doc(
                "The minor units of the currency.\nIt represents the number of decimals of the currency. For the currencies CLP, COP and HUF, the minor unit is0.\nMin: 0"
            ),
        ]
    ]
    value: typing_extensions.Required[
        typing_extensions.Annotated[
            int, typing_extensions.Doc("Integer value of the amount.\nMin: 0")
        ]
    ]


class CreateReaderCheckoutBodyInput(typing_extensions.TypedDict, total=False):
    """
    Reader Checkout
    """

    total_amount: typing_extensions.Required[
        typing_extensions.Annotated[
            CreateReaderCheckoutBodyTotalAmountInput,
            typing_extensions.Doc(
                "Amount structure.\n\nThe amount is represented as an integer value altogether with the currency and the minor unit.\n\nFor example, EUR 1.00 is represented as value 100 with minor unit of 2."
            ),
        ]
    ]
    aade: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateReaderCheckoutBodyAadeInput,
            typing_extensions.Doc(
                "Optional object containing data for transactions from ERP integrators in Greece that comply with the AADE1155 protocol.\nWhen such regulatory/business requirements apply, this object must be provided and contains the data needed tovalidate the transaction with the AADE signature provider."
            ),
        ]
    ]
    affiliate: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateReaderCheckoutBodyAffiliateInput,
            typing_extensions.Doc(
                "Affiliate metadata for the transaction.\nIt is a field that allow for integrators to track the source of the transaction."
            ),
        ]
    ]
    card_type: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateReaderCheckoutBodyCardTypeInput,
            typing_extensions.Doc(
                "The card type of the card used for the transaction.\nIs is required only for some countries (e.g: Brazil)."
            ),
        ]
    ]
    description: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc("Description of the checkout to be shown in the Merchant Sales"),
        ]
    ]
    installments: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            int,
            typing_extensions.Doc(
                "Number of installments for the transaction.\nIt may vary according to the merchant country.\nFor example, in Brazil, the maximum number of installments is 12.\n\nOmit if the merchant country does support installments.\nOtherwise, the checkout will be rejected.\nMin: 1"
            ),
        ]
    ]
    return_url: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Webhook URL to which the payment result will be sent.\nIt must be a HTTPS url.\nFormat: uri"
            ),
        ]
    ]
    tip_rates: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            typing.Sequence[float],
            typing_extensions.Doc(
                "List of tipping rates to be displayed to the cardholder.\nThe rates are in percentage and should be between 0.01 and 0.99.\nThe list should be sorted in ascending order."
            ),
        ]
    ]
    tip_timeout: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            int,
            typing_extensions.Doc(
                "Time in seconds the cardholder has to select a tip rate.\nIf not provided, the default value is 30 seconds.\n\nIt can only be set if `tip_rates` is provided.\n\n**Note**: If the target device is a Solo, it must be in version 3.3.38.0 or higher.\nDefault: 30\n\nMin: 30\nMax: 120"
            ),
        ]
    ]


class ListReaders200Response(pydantic.BaseModel):
    """
    ListReaders200Response is a schema definition.
    """

    items: list[Reader]


class ListReaders200ResponseDict(typing_extensions.TypedDict, total=False):
    items: typing_extensions.Required[typing.Sequence[ReaderInput]]


ListReaders200ResponseInput = ListReaders200ResponseDict


class ReadersResource(Resource):
    """API resource for the Readers endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def list(
        self, merchant_code: str, headers: typing.Optional[HeaderTypes] = None
    ) -> ListReaders200Response:
        """
        List Readers

        List all readers of the merchant.
        """
        resp = self._client.get(
            f"/v0.1/merchants/{merchant_code}/readers",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListReaders200Response).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def create(
        self,
        merchant_code: str,
        *,
        pairing_code: ReaderPairingCodeInput,
        name: ReaderNameInput,
        metadata: typing.Union[MetadataInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Reader:
        """
        Create a Reader

        Create a new Reader for the merchant account.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["pairing_code"] = pairing_code
        body_data["name"] = name
        if not isinstance(metadata, NotGivenType):
            body_data["metadata"] = metadata

        resp = self._client.post(
            f"/v0.1/merchants/{merchant_code}/readers",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(Reader).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError("The request is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "There's no pending reader for the submitted pairing code.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 409:
            raise APIError(
                "The Reader is not in a pending state.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def get(
        self, merchant_code: str, id: ReaderId, headers: typing.Optional[HeaderTypes] = None
    ) -> Reader:
        """
        Retrieve a Reader

        Retrieve a Reader.
        """
        resp = self._client.get(
            f"/v0.1/merchants/{merchant_code}/readers/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Reader).validate_python(resp.json())
        elif resp.status_code == 404:
            raise APIError(
                "The requested Reader resource does not exist.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def delete(
        self, merchant_code: str, id: ReaderId, headers: typing.Optional[HeaderTypes] = None
    ):
        """
        Delete a reader

        Delete a reader.
        """
        resp = self._client.delete(
            f"/v0.1/merchants/{merchant_code}/readers/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return
        elif resp.status_code == 404:
            raise APIError(
                "The requested Reader resource does not exist.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def update(
        self,
        merchant_code: str,
        id: ReaderId,
        *,
        name: typing.Union[ReaderNameInput, NotGivenType] = NOT_GIVEN,
        metadata: typing.Union[MetadataInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Reader:
        """
        Update a Reader

        Update a Reader.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(name, NotGivenType):
            body_data["name"] = name
        if not isinstance(metadata, NotGivenType):
            body_data["metadata"] = metadata

        resp = self._client.patch(
            f"/v0.1/merchants/{merchant_code}/readers/{id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Reader).validate_python(resp.json())
        elif resp.status_code == 403:
            raise APIError(
                "The request isn't sufficiently authorized to modify the reader.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested Reader resource does not exist.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def create_checkout(
        self,
        merchant_code: str,
        reader_id: str,
        *,
        aade: typing.Union[CreateReaderCheckoutBodyAadeInput, NotGivenType] = NOT_GIVEN,
        affiliate: typing.Union[CreateReaderCheckoutBodyAffiliateInput, NotGivenType] = NOT_GIVEN,
        card_type: typing.Union[CreateReaderCheckoutBodyCardTypeInput, NotGivenType] = NOT_GIVEN,
        description: typing.Union[str, NotGivenType] = NOT_GIVEN,
        installments: typing.Union[int, NotGivenType] = NOT_GIVEN,
        return_url: typing.Union[str, NotGivenType] = NOT_GIVEN,
        tip_rates: typing.Union[typing.Sequence[float], NotGivenType] = NOT_GIVEN,
        tip_timeout: typing.Union[int, NotGivenType] = NOT_GIVEN,
        total_amount: CreateReaderCheckoutBodyTotalAmountInput,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> CreateReaderCheckoutResponse:
        """
        Create a Reader Checkout

        Creates a Checkout for a Reader.

        This process is asynchronous and the actual transaction may take some time to be started on the device.


        There are some caveats when using this endpoint:
        * The target device must be online, otherwise checkout won't be accepted
        * After the checkout is accepted, the system has 60 seconds to start the payment on the target device. Duringthis time, any other checkout for the same device will be rejected.


        **Note**: If the target device is a Solo, it must be in version 3.3.24.3 or higher.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(aade, NotGivenType):
            body_data["aade"] = aade
        if not isinstance(affiliate, NotGivenType):
            body_data["affiliate"] = affiliate
        if not isinstance(card_type, NotGivenType):
            body_data["card_type"] = card_type
        if not isinstance(description, NotGivenType):
            body_data["description"] = description
        if not isinstance(installments, NotGivenType):
            body_data["installments"] = installments
        if not isinstance(return_url, NotGivenType):
            body_data["return_url"] = return_url
        if not isinstance(tip_rates, NotGivenType):
            body_data["tip_rates"] = list(tip_rates)
        if not isinstance(tip_timeout, NotGivenType):
            body_data["tip_timeout"] = tip_timeout
        body_data["total_amount"] = total_amount

        resp = self._client.post(
            f"/v0.1/merchants/{merchant_code}/readers/{reader_id}/checkout",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(CreateReaderCheckoutResponse).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError("Unauthorized", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "Response when given reader is not found", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 422:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def get_status(
        self, merchant_code: str, reader_id: str, headers: typing.Optional[HeaderTypes] = None
    ) -> StatusResponse:
        """
        Get a Reader Status

        Provides the last known status for a Reader.

        This endpoint allows you to retrieve updates from the connected card reader, including the current screen beingdisplayed during the payment process and the device status (battery level, connectivity, and update state).

        Supported States

        * `IDLE` – Reader ready for next transaction
        * `SELECTING_TIP` – Waiting for tip input
        * `WAITING_FOR_CARD` – Awaiting card insert/tap
        * `WAITING_FOR_PIN` – Waiting for PIN entry
        * `WAITING_FOR_SIGNATURE` – Waiting for customer signature
        * `UPDATING_FIRMWARE` – Firmware update in progress

        Device Status

        * `ONLINE` – Device connected and operational
        * `OFFLINE` – Device disconnected (last state persisted)

        **Note**: If the target device is a Solo, it must be in version 3.3.39.0 or higher.
        """
        resp = self._client.get(
            f"/v0.1/merchants/{merchant_code}/readers/{reader_id}/status",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(StatusResponse).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "Response when given merchant's token is invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "Response when given reader is not found", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def terminate_checkout(
        self, merchant_code: str, reader_id: str, headers: typing.Optional[HeaderTypes] = None
    ):
        """
        Terminate a Reader Checkout

        Terminate a Reader Checkout stops the current transaction on the target device.

        This process is asynchronous and the actual termination may take some time to be performed on the device.


        There are some caveats when using this endpoint:
        * The target device must be online, otherwise terminate won't be accepted
        * The action will succeed only if the device is waiting for cardholder action: e.g: waiting for card, waiting forPIN, etc.
        * There is no confirmation of the termination.

        If a transaction is successfully terminated and `return_url` was provided on Checkout, the transaction status willbe sent as `failed` to the provided URL.


        **Note**: If the target device is a Solo, it must be in version 3.3.28.0 or higher.
        """
        resp = self._client.post(
            f"/v0.1/merchants/{merchant_code}/readers/{reader_id}/terminate",
            headers=headers,
        )
        if resp.status_code == 202:
            return
        elif resp.status_code == 400:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError("Unauthorized", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "Response when given reader is not found", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 422:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncReadersResource(AsyncResource):
    """Async API resource for the Readers endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def list(
        self, merchant_code: str, headers: typing.Optional[HeaderTypes] = None
    ) -> ListReaders200Response:
        """
        List Readers

        List all readers of the merchant.
        """
        resp = await self._client.get(
            f"/v0.1/merchants/{merchant_code}/readers",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListReaders200Response).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "Authentication failed or missing required scope.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def create(
        self,
        merchant_code: str,
        *,
        pairing_code: ReaderPairingCodeInput,
        name: ReaderNameInput,
        metadata: typing.Union[MetadataInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Reader:
        """
        Create a Reader

        Create a new Reader for the merchant account.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["pairing_code"] = pairing_code
        body_data["name"] = name
        if not isinstance(metadata, NotGivenType):
            body_data["metadata"] = metadata

        resp = await self._client.post(
            f"/v0.1/merchants/{merchant_code}/readers",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(Reader).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError("The request is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "There's no pending reader for the submitted pairing code.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 409:
            raise APIError(
                "The Reader is not in a pending state.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def get(
        self, merchant_code: str, id: ReaderId, headers: typing.Optional[HeaderTypes] = None
    ) -> Reader:
        """
        Retrieve a Reader

        Retrieve a Reader.
        """
        resp = await self._client.get(
            f"/v0.1/merchants/{merchant_code}/readers/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Reader).validate_python(resp.json())
        elif resp.status_code == 404:
            raise APIError(
                "The requested Reader resource does not exist.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def delete(
        self, merchant_code: str, id: ReaderId, headers: typing.Optional[HeaderTypes] = None
    ):
        """
        Delete a reader

        Delete a reader.
        """
        resp = await self._client.delete(
            f"/v0.1/merchants/{merchant_code}/readers/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return
        elif resp.status_code == 404:
            raise APIError(
                "The requested Reader resource does not exist.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def update(
        self,
        merchant_code: str,
        id: ReaderId,
        *,
        name: typing.Union[ReaderNameInput, NotGivenType] = NOT_GIVEN,
        metadata: typing.Union[MetadataInput, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Reader:
        """
        Update a Reader

        Update a Reader.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(name, NotGivenType):
            body_data["name"] = name
        if not isinstance(metadata, NotGivenType):
            body_data["metadata"] = metadata

        resp = await self._client.patch(
            f"/v0.1/merchants/{merchant_code}/readers/{id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Reader).validate_python(resp.json())
        elif resp.status_code == 403:
            raise APIError(
                "The request isn't sufficiently authorized to modify the reader.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested Reader resource does not exist.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def create_checkout(
        self,
        merchant_code: str,
        reader_id: str,
        *,
        aade: typing.Union[CreateReaderCheckoutBodyAadeInput, NotGivenType] = NOT_GIVEN,
        affiliate: typing.Union[CreateReaderCheckoutBodyAffiliateInput, NotGivenType] = NOT_GIVEN,
        card_type: typing.Union[CreateReaderCheckoutBodyCardTypeInput, NotGivenType] = NOT_GIVEN,
        description: typing.Union[str, NotGivenType] = NOT_GIVEN,
        installments: typing.Union[int, NotGivenType] = NOT_GIVEN,
        return_url: typing.Union[str, NotGivenType] = NOT_GIVEN,
        tip_rates: typing.Union[typing.Sequence[float], NotGivenType] = NOT_GIVEN,
        tip_timeout: typing.Union[int, NotGivenType] = NOT_GIVEN,
        total_amount: CreateReaderCheckoutBodyTotalAmountInput,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> CreateReaderCheckoutResponse:
        """
        Create a Reader Checkout

        Creates a Checkout for a Reader.

        This process is asynchronous and the actual transaction may take some time to be started on the device.


        There are some caveats when using this endpoint:
        * The target device must be online, otherwise checkout won't be accepted
        * After the checkout is accepted, the system has 60 seconds to start the payment on the target device. Duringthis time, any other checkout for the same device will be rejected.


        **Note**: If the target device is a Solo, it must be in version 3.3.24.3 or higher.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(aade, NotGivenType):
            body_data["aade"] = aade
        if not isinstance(affiliate, NotGivenType):
            body_data["affiliate"] = affiliate
        if not isinstance(card_type, NotGivenType):
            body_data["card_type"] = card_type
        if not isinstance(description, NotGivenType):
            body_data["description"] = description
        if not isinstance(installments, NotGivenType):
            body_data["installments"] = installments
        if not isinstance(return_url, NotGivenType):
            body_data["return_url"] = return_url
        if not isinstance(tip_rates, NotGivenType):
            body_data["tip_rates"] = list(tip_rates)
        if not isinstance(tip_timeout, NotGivenType):
            body_data["tip_timeout"] = tip_timeout
        body_data["total_amount"] = total_amount

        resp = await self._client.post(
            f"/v0.1/merchants/{merchant_code}/readers/{reader_id}/checkout",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(CreateReaderCheckoutResponse).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError("Unauthorized", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "Response when given reader is not found", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 422:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def get_status(
        self, merchant_code: str, reader_id: str, headers: typing.Optional[HeaderTypes] = None
    ) -> StatusResponse:
        """
        Get a Reader Status

        Provides the last known status for a Reader.

        This endpoint allows you to retrieve updates from the connected card reader, including the current screen beingdisplayed during the payment process and the device status (battery level, connectivity, and update state).

        Supported States

        * `IDLE` – Reader ready for next transaction
        * `SELECTING_TIP` – Waiting for tip input
        * `WAITING_FOR_CARD` – Awaiting card insert/tap
        * `WAITING_FOR_PIN` – Waiting for PIN entry
        * `WAITING_FOR_SIGNATURE` – Waiting for customer signature
        * `UPDATING_FIRMWARE` – Firmware update in progress

        Device Status

        * `ONLINE` – Device connected and operational
        * `OFFLINE` – Device disconnected (last state persisted)

        **Note**: If the target device is a Solo, it must be in version 3.3.39.0 or higher.
        """
        resp = await self._client.get(
            f"/v0.1/merchants/{merchant_code}/readers/{reader_id}/status",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(StatusResponse).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "Response when given merchant's token is invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "Response when given reader is not found", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def terminate_checkout(
        self, merchant_code: str, reader_id: str, headers: typing.Optional[HeaderTypes] = None
    ):
        """
        Terminate a Reader Checkout

        Terminate a Reader Checkout stops the current transaction on the target device.

        This process is asynchronous and the actual termination may take some time to be performed on the device.


        There are some caveats when using this endpoint:
        * The target device must be online, otherwise terminate won't be accepted
        * The action will succeed only if the device is waiting for cardholder action: e.g: waiting for card, waiting forPIN, etc.
        * There is no confirmation of the termination.

        If a transaction is successfully terminated and `return_url` was provided on Checkout, the transaction status willbe sent as `failed` to the provided URL.


        **Note**: If the target device is a Solo, it must be in version 3.3.28.0 or higher.
        """
        resp = await self._client.post(
            f"/v0.1/merchants/{merchant_code}/readers/{reader_id}/terminate",
            headers=headers,
        )
        if resp.status_code == 202:
            return
        elif resp.status_code == 400:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError("Unauthorized", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "Response when given reader is not found", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 422:
            raise APIError(
                "Response when given params (or one of them) are invalid",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
