# Code generated by `py-sdk-gen`. DO NOT EDIT.
from .._service import Resource, AsyncResource


class SharedResource(Resource):
    def __init__(self, client):
        super().__init__(client)


class AsyncSharedResource(AsyncResource):
    def __init__(self, client):
        super().__init__(client)
