# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
Customers represent payers in your integration. Create a customer with your own `customer_id` to associate their personal details and saved payment instruments with your business records.

To save a card, create a checkout for that customer with `purpose = SETUP_RECURRING_PAYMENT`, then process it with the payer's consent and mandate details. See the [tokenization guide](https://developer.sumup.com/online-payments/guides/tokenization-with-payment-sdk/).

Use the Customers endpoints to create, retrieve, or update customer details and to list or deactivate saved payment instruments. For subsequent payments, process a new checkout with the saved instrument's `token` and its associated `customer_id`.
"""

from __future__ import annotations

import datetime
import typing

import httpx
import pydantic
import typing_extensions

from .._exceptions import APIError
from .._service import (
    NOT_GIVEN,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    Resource,
    serialize_query_params,
    serialize_request_data,
)
from ..types import (
    AddressLegacy,
    AddressLegacyInput,
    CardType,
    Customer,
    CustomerInput,
    Error,
    ErrorExtended,
    ErrorForbidden,
    MandateResponse,
    PaymentInstrumentResponse,
    PersonalDetails,
    PersonalDetailsInput,
    Problem,
)


class CreateCustomerBodyInput(typing_extensions.TypedDict, total=False):
    """
    Saved payer details identified by the `customer_id` supplied by your integration. A customer can have savedpayment instruments for subsequent payments.
    """

    customer_id: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Identifier you supply when creating the customer. Use an ID from your own system and retain it for subsequent customer,checkout, and saved-payment-instrument requests."
            ),
        ]
    ]
    personal_details: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            PersonalDetailsInput, typing_extensions.Doc("Personal details for the customer.")
        ]
    ]


class UpdateCustomerBodyInput(typing_extensions.TypedDict, total=False):
    """
    UpdateCustomerBody is a schema definition.
    """

    personal_details: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            PersonalDetailsInput, typing_extensions.Doc("Personal details for the customer.")
        ]
    ]


ListPaymentInstruments200Response = list[PaymentInstrumentResponse]
"""
ListPaymentInstruments200Response is a schema definition.
"""


class CustomersResource(Resource):
    """API resource for the Customers endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def create(
        self,
        *,
        customer_id: str,
        personal_details: PersonalDetailsInput | None | NotGivenType = NOT_GIVEN,
        headers: HeaderTypes | None = None,
    ) -> Customer:
        """
        Create a customer

        Creates a customer using the `customer_id` you supply. Choose an identifier that maps to the payer in your own systemand reuse it when retrieving the customer or associating checkouts and saved payment instruments with them.


        Raises:
           APIError: Raised when the API returns one of the documented error responses:
                400: The request body is invalid.
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                409: A customer with the provided identifier already exists.
                Unexpected response statuses also raise this exception.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["customer_id"] = customer_id
        if not isinstance(personal_details, NotGivenType):
            body_data["personal_details"] = personal_details

        resp = self._client.post(
            f"/v0.1/customers",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(Customer).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError("The request body is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 409:
            raise APIError(
                "A customer with the provided identifier already exists.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def get(self, customer_id: str, headers: HeaderTypes | None = None) -> Customer:
        """
        Retrieve a customer

        Retrieves a saved customer using the `customer_id` you supplied when creating the customer.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        resp = self._client.get(
            f"/v0.1/customers/{customer_id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Customer).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def update(
        self,
        customer_id: str,
        *,
        personal_details: PersonalDetailsInput | None | NotGivenType = NOT_GIVEN,
        headers: HeaderTypes | None = None,
    ) -> Customer:
        """
        Update a customer

        Updates an identified saved customer resource's personal details.

        The request only overwrites the parameters included in the request, all other parameters will remain with theirinitially assigned values.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(personal_details, NotGivenType):
            body_data["personal_details"] = personal_details

        resp = self._client.put(
            f"/v0.1/customers/{customer_id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Customer).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def list_payment_instruments(
        self, customer_id: str, headers: HeaderTypes | None = None
    ) -> ListPaymentInstruments200Response:
        """
        List payment instruments

        Lists all payment instrument resources that are saved for an identified customer.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        resp = self._client.get(
            f"/v0.1/customers/{customer_id}/payment-instruments",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListPaymentInstruments200Response).validate_python(
                resp.json()
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def deactivate_payment_instrument(
        self, customer_id: str, token: str, headers: HeaderTypes | None = None
    ):
        """
        Deactivate a payment instrument

        Deactivates an identified card payment instrument resource for a customer.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                400: The request is invalid.
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        resp = self._client.delete(
            f"/v0.1/customers/{customer_id}/payment-instruments/{token}",
            headers=headers,
        )
        if resp.status_code == 204:
            return
        elif resp.status_code == 400:
            raise APIError("The request is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncCustomersResource(AsyncResource):
    """Async API resource for the Customers endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def create(
        self,
        *,
        customer_id: str,
        personal_details: PersonalDetailsInput | None | NotGivenType = NOT_GIVEN,
        headers: HeaderTypes | None = None,
    ) -> Customer:
        """
        Create a customer

        Creates a customer using the `customer_id` you supply. Choose an identifier that maps to the payer in your own systemand reuse it when retrieving the customer or associating checkouts and saved payment instruments with them.


        Raises:
           APIError: Raised when the API returns one of the documented error responses:
                400: The request body is invalid.
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                409: A customer with the provided identifier already exists.
                Unexpected response statuses also raise this exception.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["customer_id"] = customer_id
        if not isinstance(personal_details, NotGivenType):
            body_data["personal_details"] = personal_details

        resp = await self._client.post(
            f"/v0.1/customers",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(Customer).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError("The request body is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 409:
            raise APIError(
                "A customer with the provided identifier already exists.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def get(self, customer_id: str, headers: HeaderTypes | None = None) -> Customer:
        """
        Retrieve a customer

        Retrieves a saved customer using the `customer_id` you supplied when creating the customer.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        resp = await self._client.get(
            f"/v0.1/customers/{customer_id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Customer).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def update(
        self,
        customer_id: str,
        *,
        personal_details: PersonalDetailsInput | None | NotGivenType = NOT_GIVEN,
        headers: HeaderTypes | None = None,
    ) -> Customer:
        """
        Update a customer

        Updates an identified saved customer resource's personal details.

        The request only overwrites the parameters included in the request, all other parameters will remain with theirinitially assigned values.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(personal_details, NotGivenType):
            body_data["personal_details"] = personal_details

        resp = await self._client.put(
            f"/v0.1/customers/{customer_id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Customer).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def list_payment_instruments(
        self, customer_id: str, headers: HeaderTypes | None = None
    ) -> ListPaymentInstruments200Response:
        """
        List payment instruments

        Lists all payment instrument resources that are saved for an identified customer.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        resp = await self._client.get(
            f"/v0.1/customers/{customer_id}/payment-instruments",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListPaymentInstruments200Response).validate_python(
                resp.json()
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def deactivate_payment_instrument(
        self, customer_id: str, token: str, headers: HeaderTypes | None = None
    ):
        """
        Deactivate a payment instrument

        Deactivates an identified card payment instrument resource for a customer.


        Raises:
            APIError: Raised when the API returns one of the documented error responses:
                400: The request is invalid.
                401: The request is not authorized.
                403: The request is authenticated but not permitted for this operation.
                404: The requested resource does not exist.
                Unexpected response statuses also raise this exception.
        """
        resp = await self._client.delete(
            f"/v0.1/customers/{customer_id}/payment-instruments/{token}",
            headers=headers,
        )
        if resp.status_code == 204:
            return
        elif resp.status_code == 400:
            raise APIError("The request is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request is authenticated but not permitted for this operation.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
