# Code generated by `py-sdk-gen`. DO NOT EDIT.
from .. import _shared
import datetime
import typing
import pydantic


class Customer(pydantic.BaseModel):
    """
    Customer is a schema definition.
    """

    customer_id: str
    """
	Unique ID of the customer.
	"""

    personal_details: typing.Optional[_shared.PersonalDetails] = None
    """
	Personal details for the customer.
	"""


PaymentInstrumentResponseType = typing.Literal["card"]


class PaymentInstrumentResponseCard(pydantic.BaseModel):
    """
    Details of the payment card.
    """

    last_4_digits: typing.Optional[str] = None
    """
	Last 4 digits of the payment card number.
	Read only
	Min length: 4
	Max length: 4
	"""

    type: typing.Optional[_shared.CardType] = None
    """
	Issuing card network of the payment card used for the transaction.
	"""


class PaymentInstrumentResponse(pydantic.BaseModel):
    """
    Payment Instrument Response
    """

    active: typing.Optional[bool] = None
    """
	Indicates whether the payment instrument is active and can be used for payments. To deactivate it, send a`DELETE` request to the resource endpoint.
	Read only
	Default: true
	"""

    card: typing.Optional[PaymentInstrumentResponseCard] = None
    """
	Details of the payment card.
	"""

    created_at: typing.Optional[datetime.datetime] = None
    """
	Creation date of payment instrument. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.
	"""

    mandate: typing.Optional[_shared.MandateResponse] = None
    """
	Created mandate
	"""

    token: typing.Optional[str] = None
    """
	Unique token identifying the saved payment card for a customer.
	Read only
	"""

    type: typing.Optional[PaymentInstrumentResponseType] = None
    """
	Type of the payment instrument.
	"""
