# Code generated by `py-sdk-gen`. DO NOT EDIT.
import os
import typing

import httpx

from ._service import AsyncResource, Resource, runtime_headers

if typing.TYPE_CHECKING:
    from .events import (
        AsyncEventCallback,
        AsyncEventsHandler,
        EventBody,
        EventCallback,
        EventNotification,
        EventsHandler,
    )
from .checkouts import AsyncCheckoutsResource, CheckoutsResource
from .customers import AsyncCustomersResource, CustomersResource
from .members import AsyncMembersResource, MembersResource
from .memberships import AsyncMembershipsResource, MembershipsResource
from .merchants import AsyncMerchantsResource, MerchantsResource
from .payouts import AsyncPayoutsResource, PayoutsResource
from .readers import AsyncReadersResource, ReadersResource
from .receipts import AsyncReceiptsResource, ReceiptsResource
from .roles import AsyncRolesResource, RolesResource
from .transactions import AsyncTransactionsResource, TransactionsResource

BASE_URL = "https://api.sumup.com"
TimeoutType = (
    httpx.Timeout
    | float
    | tuple[
        float | None,
        float | None,
        float | None,
        float | None,
    ]
)


class Sumup(Resource):
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str = BASE_URL,
        timeout: TimeoutType | None = None,
    ) -> None:
        self.api_key = api_key or os.getenv("SUMUP_API_KEY")
        super().__init__(
            httpx.Client(
                base_url=base_url,
                timeout=timeout,
                headers={
                    "Accept": "application/problem+json, application/json",
                    "User-Agent": f"sumup-py/{self.version()}",
                    "Authorization": f"Bearer {self.api_key}",
                    **runtime_headers(),
                },
            )
        )

    def events_handler(
        self,
        secret: str,
        fallback: "EventCallback",
    ) -> "EventsHandler":
        """Create a synchronous event handler bound to this API client.

        Register typed callbacks with decorators such as @handler.on_reader_created,
        then call handler.handle(body, signature) in your HTTP route. Callbacks receive
        one event and can use event.fetch_object() to retrieve its current resource.

        Args:
            secret: Event signing secret, separate from your API key. Required; the SDK
                does not read a signing secret from environment variables.
            fallback: Required synchronous callback for unknown event types and known
                types without a registered callback. Return None on success or raise.

        Returns:
            An EventsHandler ready for callback registration.

        Raises:
            EventSignatureError: The signing secret is missing or empty.
            EventHandlerRegistrationError: The fallback is not callable.
        """
        from .events import EventsHandler

        return EventsHandler(
            secret=secret,
            fallback=fallback,
            client=self._client,
        )

    def parse_event_notification(
        self, body: "EventBody", signature: str | None, secret: str
    ) -> "EventNotification":
        """Verify and parse an incoming event without running callbacks.

        Performs no network requests and is synchronous, including on AsyncSumup.
        For deliveries already verified before storage, use
        parse_event_notification_without_verification().

        Args:
            body: Unchanged request bytes or a UTF-8 string, read before JSON parsing.
            signature: Complete X-SumUp-Webhook-Signature header value. None is accepted
                for framework compatibility but raises EventSignatureError.
            secret: Event signing secret, separate from your API key.

        Returns:
            A typed event bound to this client, or UnknownEvent for an unrecognized type.

        Raises:
            EventSignatureError: Missing secret, invalid signature, or a signing timestamp
                more than five minutes before or after the receiver's clock.
            EventPayloadError: Invalid raw input, UTF-8, JSON, or event fields.
        """
        from ._events import parse_event_notification

        return parse_event_notification(secret, body, signature, client=self._client)

    def parse_event_notification_without_verification(
        self, body: "EventBody"
    ) -> "EventNotification":
        """Parse a trusted event without checking its signature or signing timestamp.

        Use only for fixtures or deliveries already verified before storage in a trusted
        queue. For incoming HTTP requests, use parse_event_notification() instead.
        This method is synchronous, including on AsyncSumup, and performs no network I/O.

        Args:
            body: The raw event JSON as bytes or a UTF-8 string.

        Returns:
            A typed event bound to this client, or UnknownEvent for an unrecognized type.

        Raises:
            EventPayloadError: Invalid raw input, UTF-8, JSON, or event fields.
        """
        from ._events import parse_event_notification_without_verification

        return parse_event_notification_without_verification(body, client=self._client)

    @property
    def checkouts(self) -> CheckoutsResource:
        """Access the Checkouts API endpoints."""
        from .checkouts.resource import CheckoutsResource

        return CheckoutsResource(self._client)

    @property
    def customers(self) -> CustomersResource:
        """Access the Customers API endpoints."""
        from .customers.resource import CustomersResource

        return CustomersResource(self._client)

    @property
    def members(self) -> MembersResource:
        """Access the Members API endpoints."""
        from .members.resource import MembersResource

        return MembersResource(self._client)

    @property
    def memberships(self) -> MembershipsResource:
        """Access the Memberships API endpoints."""
        from .memberships.resource import MembershipsResource

        return MembershipsResource(self._client)

    @property
    def merchants(self) -> MerchantsResource:
        """Access the Merchants API endpoints."""
        from .merchants.resource import MerchantsResource

        return MerchantsResource(self._client)

    @property
    def payouts(self) -> PayoutsResource:
        """Access the Payouts API endpoints."""
        from .payouts.resource import PayoutsResource

        return PayoutsResource(self._client)

    @property
    def readers(self) -> ReadersResource:
        """Access the Readers API endpoints."""
        from .readers.resource import ReadersResource

        return ReadersResource(self._client)

    @property
    def receipts(self) -> ReceiptsResource:
        """Access the Receipts API endpoints."""
        from .receipts.resource import ReceiptsResource

        return ReceiptsResource(self._client)

    @property
    def roles(self) -> RolesResource:
        """Access the Roles API endpoints."""
        from .roles.resource import RolesResource

        return RolesResource(self._client)

    @property
    def transactions(self) -> TransactionsResource:
        """Access the Transactions API endpoints."""
        from .transactions.resource import TransactionsResource

        return TransactionsResource(self._client)


class AsyncSumup(AsyncResource):
    def __init__(
        self,
        api_key: str | None = None,
        base_url: str = BASE_URL,
        timeout: TimeoutType | None = None,
    ) -> None:
        self.api_key = api_key or os.getenv("SUMUP_API_KEY")
        super().__init__(
            httpx.AsyncClient(
                base_url=base_url,
                timeout=timeout,
                headers={
                    "Accept": "application/problem+json, application/json",
                    "User-Agent": f"sumup-py/{self.version()}",
                    "Authorization": f"Bearer {self.api_key}",
                    **runtime_headers(),
                },
            )
        )

    def events_handler(
        self,
        secret: str,
        fallback: "AsyncEventCallback",
    ) -> "AsyncEventsHandler":
        """Create an asynchronous event handler bound to this API client.

        Register async callbacks with decorators such as @handler.on_reader_created,
        then await handler.handle(body, signature) in your HTTP route. Callbacks can
        await event.fetch_object_async() to retrieve the current resource.

        Args:
            secret: Event signing secret, separate from your API key. Required; the SDK
                does not read a signing secret from environment variables.
            fallback: Required async callback for unknown event types and known types
                without a registered callback. It is awaited before handling completes.

        Returns:
            An AsyncEventsHandler ready for callback registration.

        Raises:
            EventSignatureError: The signing secret is missing or empty.
            EventHandlerRegistrationError: The fallback is not callable.
        """
        from .events import AsyncEventsHandler

        return AsyncEventsHandler(
            secret=secret,
            fallback=fallback,
            client=self._client,
        )

    def parse_event_notification(
        self, body: "EventBody", signature: str | None, secret: str
    ) -> "EventNotification":
        """Verify and parse an incoming event without running callbacks.

        Performs no network requests and is synchronous, including on AsyncSumup.
        For deliveries already verified before storage, use
        parse_event_notification_without_verification().

        Args:
            body: Unchanged request bytes or a UTF-8 string, read before JSON parsing.
            signature: Complete X-SumUp-Webhook-Signature header value. None is accepted
                for framework compatibility but raises EventSignatureError.
            secret: Event signing secret, separate from your API key.

        Returns:
            A typed event bound to this client, or UnknownEvent for an unrecognized type.

        Raises:
            EventSignatureError: Missing secret, invalid signature, or a signing timestamp
                more than five minutes before or after the receiver's clock.
            EventPayloadError: Invalid raw input, UTF-8, JSON, or event fields.
        """
        from ._events import parse_event_notification

        return parse_event_notification(secret, body, signature, client=self._client)

    def parse_event_notification_without_verification(
        self, body: "EventBody"
    ) -> "EventNotification":
        """Parse a trusted event without checking its signature or signing timestamp.

        Use only for fixtures or deliveries already verified before storage in a trusted
        queue. For incoming HTTP requests, use parse_event_notification() instead.
        This method is synchronous, including on AsyncSumup, and performs no network I/O.

        Args:
            body: The raw event JSON as bytes or a UTF-8 string.

        Returns:
            A typed event bound to this client, or UnknownEvent for an unrecognized type.

        Raises:
            EventPayloadError: Invalid raw input, UTF-8, JSON, or event fields.
        """
        from ._events import parse_event_notification_without_verification

        return parse_event_notification_without_verification(body, client=self._client)

    @property
    def checkouts(self) -> AsyncCheckoutsResource:
        """Access the Checkouts API endpoints."""
        from .checkouts.resource import AsyncCheckoutsResource

        return AsyncCheckoutsResource(self._client)

    @property
    def customers(self) -> AsyncCustomersResource:
        """Access the Customers API endpoints."""
        from .customers.resource import AsyncCustomersResource

        return AsyncCustomersResource(self._client)

    @property
    def members(self) -> AsyncMembersResource:
        """Access the Members API endpoints."""
        from .members.resource import AsyncMembersResource

        return AsyncMembersResource(self._client)

    @property
    def memberships(self) -> AsyncMembershipsResource:
        """Access the Memberships API endpoints."""
        from .memberships.resource import AsyncMembershipsResource

        return AsyncMembershipsResource(self._client)

    @property
    def merchants(self) -> AsyncMerchantsResource:
        """Access the Merchants API endpoints."""
        from .merchants.resource import AsyncMerchantsResource

        return AsyncMerchantsResource(self._client)

    @property
    def payouts(self) -> AsyncPayoutsResource:
        """Access the Payouts API endpoints."""
        from .payouts.resource import AsyncPayoutsResource

        return AsyncPayoutsResource(self._client)

    @property
    def readers(self) -> AsyncReadersResource:
        """Access the Readers API endpoints."""
        from .readers.resource import AsyncReadersResource

        return AsyncReadersResource(self._client)

    @property
    def receipts(self) -> AsyncReceiptsResource:
        """Access the Receipts API endpoints."""
        from .receipts.resource import AsyncReceiptsResource

        return AsyncReceiptsResource(self._client)

    @property
    def roles(self) -> AsyncRolesResource:
        """Access the Roles API endpoints."""
        from .roles.resource import AsyncRolesResource

        return AsyncRolesResource(self._client)

    @property
    def transactions(self) -> AsyncTransactionsResource:
        """Access the Transactions API endpoints."""
        from .transactions.resource import AsyncTransactionsResource

        return AsyncTransactionsResource(self._client)
