from __future__ import annotations

import datetime as dt
import hashlib
import hmac
import threading
import typing

import httpx
import pydantic

from ._exceptions import APIError, SumupError

if typing.TYPE_CHECKING:
    from ._client import AsyncSumup, Sumup


SIGNATURE_HEADER = "X-SumUp-Webhook-Signature"
TIMESTAMP_HEADER = "X-SumUp-Webhook-Timestamp"
SIGNATURE_VERSION = "v1"
DEFAULT_TOLERANCE = dt.timedelta(minutes=5)

_UTC = dt.timezone.utc
_Body = typing.Union[bytes, bytearray, memoryview]
_ObjectT = typing.TypeVar("_ObjectT", bound=pydantic.BaseModel)


class EventError(SumupError):
    """Base class for event verification and handling failures."""


class EventTimestampError(EventError):
    """Raised when the event timestamp header is missing or malformed."""


class EventSignatureError(EventError):
    """Raised when the event signature is missing or invalid."""


class EventSignatureExpiredError(EventSignatureError):
    """Raised when the event timestamp is outside the allowed tolerance."""


class EventHandlerRegistrationError(EventError):
    """Raised when an event callback cannot be registered."""


class EventObjectUrlError(EventError):
    """Raised when an event references an object outside the API host."""


class EventObject(pydantic.BaseModel):
    """Reference to the SumUp resource associated with an event notification."""

    id: str
    type: str
    url: str


class EventNotification(pydantic.BaseModel):
    """Event notification envelope received from SumUp."""

    id: str
    type: str
    created_at: dt.datetime
    object: EventObject

    _client: typing.Optional[typing.Union[httpx.Client, httpx.AsyncClient]] = pydantic.PrivateAttr(
        default=None
    )

    def _bind_client(self, client: object) -> EventNotification:
        self._client = _unwrap_client(client)
        return self


class UnknownEvent(EventNotification):
    """Event notification whose type is not generated by this SDK version."""


class FetchableEvent(EventNotification, typing.Generic[_ObjectT]):
    """Generated event notification with a fetchable API resource."""

    EVENT_TYPE: typing.ClassVar[str]
    _response_model: typing.ClassVar[typing.Type[pydantic.BaseModel]]

    def _require_sync_client(self) -> httpx.Client:
        if self._client is None:
            raise RuntimeError("event notification is not bound to a SumUp client")
        if not isinstance(self._client, httpx.Client):
            raise RuntimeError(
                "event notification is bound to an async client; use fetch_object_async()"
            )
        return self._client

    def _require_async_client(self) -> httpx.AsyncClient:
        if self._client is None:
            raise RuntimeError("event notification is not bound to a SumUp client")
        if not isinstance(self._client, httpx.AsyncClient):
            raise RuntimeError("event notification is bound to a sync client; use fetch_object()")
        return self._client

    def _parse_response(self, response: httpx.Response) -> _ObjectT:
        if response.status_code != 200:
            raise APIError("Unexpected response", status=response.status_code, body=response.text)
        return typing.cast(_ObjectT, self._response_model.model_validate(response.json()))

    def fetch_object(self) -> _ObjectT:
        """Fetch the latest state of the resource referenced by this event."""
        client = self._require_sync_client()
        response = client.get(_validated_object_url(client, self.object.url))
        return self._parse_response(response)

    async def fetch_object_async(self) -> _ObjectT:
        """Asynchronously fetch the resource referenced by this event."""
        client = self._require_async_client()
        response = await client.get(_validated_object_url(client, self.object.url))
        return self._parse_response(response)


EventCallback = typing.Callable[[EventNotification, "Sumup"], None]
AsyncEventCallback = typing.Callable[[EventNotification, "AsyncSumup"], typing.Awaitable[None]]
_EventT = typing.TypeVar("_EventT", bound=EventNotification)
_ErasedCallback = typing.Callable[[EventNotification, object], object]


class _BaseEventsHandler:
    def __init__(
        self,
        *,
        secret: str,
        fallback: _ErasedCallback,
        client: object,
        tolerance: dt.timedelta,
    ) -> None:
        self._secret = secret
        self._fallback = fallback
        self._client = client
        self.tolerance = tolerance
        self._callbacks: typing.Dict[str, _ErasedCallback] = {}
        self._handling_started = False
        self._registration_lock = threading.Lock()

    @property
    def registered_event_types(self) -> typing.Tuple[str, ...]:
        """Return event types with dedicated callbacks."""
        with self._registration_lock:
            return tuple(sorted(self._callbacks))

    def _register(
        self,
        event_model: typing.Type[EventNotification],
        callback: _ErasedCallback,
    ) -> None:
        event_type = _event_type_for_model(event_model)
        if event_type is None:
            raise EventHandlerRegistrationError(
                "event callbacks can only be registered for generated event classes"
            )

        with self._registration_lock:
            if self._handling_started:
                raise EventHandlerRegistrationError(
                    "cannot register event callbacks after handling has started"
                )
            if event_type in self._callbacks:
                raise EventHandlerRegistrationError(
                    f"callback already registered for event type: {event_type}"
                )
            self._callbacks[event_type] = callback

    def _prepare_event(
        self,
        body: _Body,
        signature_header: str,
        timestamp_header: str,
        *,
        now: typing.Optional[dt.datetime],
    ) -> typing.Tuple[EventNotification, _ErasedCallback]:
        with self._registration_lock:
            self._handling_started = True

        event = parse_event_notification(
            self._secret,
            body,
            signature_header,
            timestamp_header,
            client=self._client,
            tolerance=self.tolerance,
            now=now,
        )
        callback = self._callbacks.get(event.type, self._fallback)
        return event, callback


class EventsHandler(_BaseEventsHandler):
    """Verify and route event notifications to typed synchronous callbacks."""

    def __init__(
        self,
        *,
        secret: str,
        fallback: EventCallback,
        client: Sumup,
        tolerance: dt.timedelta = DEFAULT_TOLERANCE,
    ) -> None:
        super().__init__(
            secret=secret,
            fallback=typing.cast(_ErasedCallback, fallback),
            client=client,
            tolerance=tolerance,
        )

    @property
    def client(self) -> Sumup:
        """Return the SumUp client supplied to this handler."""
        return typing.cast("Sumup", self._client)

    def on(
        self,
        event_model: typing.Type[_EventT],
        callback: typing.Callable[[_EventT, Sumup], None],
    ) -> EventsHandler:
        """Register a callback for one generated event class."""
        self._register(event_model, typing.cast(_ErasedCallback, callback))
        return self

    def handle(
        self,
        body: _Body,
        signature_header: str,
        timestamp_header: str,
        *,
        now: typing.Optional[dt.datetime] = None,
    ) -> None:
        """Verify, parse, and route one raw event notification."""
        event, callback = self._prepare_event(
            body,
            signature_header,
            timestamp_header,
            now=now,
        )
        callback(event, self._client)


class AsyncEventsHandler(_BaseEventsHandler):
    """Verify and route event notifications to typed asynchronous callbacks."""

    def __init__(
        self,
        *,
        secret: str,
        fallback: AsyncEventCallback,
        client: AsyncSumup,
        tolerance: dt.timedelta = DEFAULT_TOLERANCE,
    ) -> None:
        super().__init__(
            secret=secret,
            fallback=typing.cast(_ErasedCallback, fallback),
            client=client,
            tolerance=tolerance,
        )

    @property
    def client(self) -> AsyncSumup:
        """Return the async SumUp client supplied to this handler."""
        return typing.cast("AsyncSumup", self._client)

    def on(
        self,
        event_model: typing.Type[_EventT],
        callback: typing.Callable[[_EventT, AsyncSumup], typing.Awaitable[None]],
    ) -> AsyncEventsHandler:
        """Register an async callback for one generated event class."""
        self._register(event_model, typing.cast(_ErasedCallback, callback))
        return self

    async def handle(
        self,
        body: _Body,
        signature_header: str,
        timestamp_header: str,
        *,
        now: typing.Optional[dt.datetime] = None,
    ) -> None:
        """Verify, parse, and route one raw event notification."""
        event, callback = self._prepare_event(
            body,
            signature_header,
            timestamp_header,
            now=now,
        )
        await typing.cast(typing.Awaitable[None], callback(event, self._client))


def verify_signature(
    secret: str,
    body: _Body,
    signature_header: str,
    timestamp_header: str,
    *,
    tolerance: dt.timedelta = DEFAULT_TOLERANCE,
    now: typing.Optional[dt.datetime] = None,
) -> None:
    """Verify an event signature and timestamp against the exact raw body."""
    if not signature_header.strip():
        raise EventSignatureError("missing event signature header")
    if not timestamp_header.strip():
        raise EventTimestampError("missing event timestamp header")

    try:
        timestamp = dt.datetime.fromtimestamp(int(timestamp_header), tz=_UTC)
    except (TypeError, ValueError) as error:
        raise EventTimestampError("invalid event timestamp") from error

    if abs(_coerce_now(now) - timestamp) > tolerance:
        raise EventSignatureExpiredError("event timestamp outside allowed tolerance")

    version, separator, digest = signature_header.partition("=")
    if separator != "=" or not version or not digest:
        raise EventSignatureError("invalid event signature format")
    if version != SIGNATURE_VERSION:
        raise EventSignatureError("unsupported event signature version")

    expected = hmac.new(
        secret.encode("utf-8"),
        _signed_content(timestamp, body),
        hashlib.sha256,
    ).hexdigest()
    if not hmac.compare_digest(expected, digest):
        raise EventSignatureError("invalid event signature")


def parse_event_notification(
    secret: str,
    body: _Body,
    signature_header: str,
    timestamp_header: str,
    *,
    client: object = None,
    tolerance: dt.timedelta = DEFAULT_TOLERANCE,
    now: typing.Optional[dt.datetime] = None,
) -> EventNotification:
    """Verify and parse an event notification into its generated event class."""
    verify_signature(
        secret,
        body,
        signature_header,
        timestamp_header,
        tolerance=tolerance,
        now=now,
    )
    return dangerously_parse_unverified_event_notification(body, client=client)


def dangerously_parse_unverified_event_notification(
    body: _Body,
    *,
    client: object = None,
) -> EventNotification:
    """Parse an event without verification for trusted fixtures and tests only."""
    payload = pydantic.TypeAdapter(typing.Dict[str, typing.Any]).validate_json(
        _coerce_body_bytes(body)
    )
    event_type = payload.get("type")
    models = _event_models()
    model = models.get(event_type, UnknownEvent) if isinstance(event_type, str) else UnknownEvent
    event = model.model_validate(payload)
    return event._bind_client(client)


def _event_models() -> typing.Mapping[str, typing.Type[EventNotification]]:
    from .events import _EVENT_MODELS

    return _EVENT_MODELS


def _event_type_for_model(event_model: typing.Type[EventNotification]) -> typing.Optional[str]:
    for event_type, generated_model in _event_models().items():
        if generated_model is event_model:
            return event_type
    return None


def _unwrap_client(
    client: object,
) -> typing.Optional[typing.Union[httpx.Client, httpx.AsyncClient]]:
    if client is None:
        return None
    if isinstance(client, (httpx.Client, httpx.AsyncClient)):
        return client

    inner_client = getattr(client, "_client", None)
    if isinstance(inner_client, (httpx.Client, httpx.AsyncClient)):
        return inner_client

    raise TypeError("client must be a SumUp client, httpx.Client, or httpx.AsyncClient")


def _validated_object_url(
    client: typing.Union[httpx.Client, httpx.AsyncClient],
    value: str,
) -> httpx.URL:
    try:
        object_url = httpx.URL(value)
    except (httpx.InvalidURL, ValueError) as error:
        raise EventObjectUrlError(f"invalid event object URL: {value}") from error

    if object_url.host != client.base_url.host:
        raise EventObjectUrlError(f"invalid event object URL: {value}")
    return object_url


def _coerce_now(now: typing.Optional[dt.datetime]) -> dt.datetime:
    if now is None:
        return dt.datetime.now(tz=_UTC)
    if now.tzinfo is None:
        return now.replace(tzinfo=_UTC)
    return now.astimezone(_UTC)


def _coerce_body_bytes(body: _Body) -> bytes:
    if isinstance(body, bytes):
        return body
    if isinstance(body, (bytearray, memoryview)):
        return bytes(body)
    raise TypeError("event body must contain the exact raw bytes received over HTTP")


def _signed_content(timestamp: dt.datetime, body: _Body) -> bytes:
    prefix = f"{SIGNATURE_VERSION}:{int(timestamp.timestamp())}:".encode("utf-8")
    return prefix + _coerce_body_bytes(body)
