# Code generated by `py-sdk-gen`. DO NOT EDIT.
from __future__ import annotations

import typing

import pydantic

from ._events import (
    AsyncEventCallback,
    AsyncEventsHandler,
    DEFAULT_TOLERANCE,
    EventCallback,
    EventError,
    EventHandlerRegistrationError,
    EventNotification,
    EventObject,
    EventObjectUrlError,
    EventSignatureError,
    EventSignatureExpiredError,
    EventTimestampError,
    EventsHandler,
    FetchableEvent,
    SIGNATURE_HEADER,
    SIGNATURE_VERSION,
    TIMESTAMP_HEADER,
    UnknownEvent,
    dangerously_parse_unverified_event_notification,
    parse_event_notification,
    verify_signature,
)
from .types import (
    Member,
    Reader,
)


class MemberCreatedEvent(FetchableEvent[Member]):
    """Sent when a member is created, invited, or accepts an invitation for a merchant account."""

    EVENT_TYPE: typing.ClassVar[str] = "members.created"
    type: typing.Literal["members.created"] = "members.created"
    _response_model: typing.ClassVar[typing.Type[pydantic.BaseModel]] = Member


class MemberDeletedEvent(FetchableEvent[Member]):
    """Sent when a member is deleted from a merchant account."""

    EVENT_TYPE: typing.ClassVar[str] = "members.deleted"
    type: typing.Literal["members.deleted"] = "members.deleted"
    _response_model: typing.ClassVar[typing.Type[pydantic.BaseModel]] = Member


class MemberUpdatedEvent(FetchableEvent[Member]):
    """Sent when a member is updated, disabled, rejected, or expires for a merchant account."""

    EVENT_TYPE: typing.ClassVar[str] = "members.updated"
    type: typing.Literal["members.updated"] = "members.updated"
    _response_model: typing.ClassVar[typing.Type[pydantic.BaseModel]] = Member


class ReaderCreatedEvent(FetchableEvent[Reader]):
    """Sent when a reader is paired to a merchant account and becomes available through the Readers API."""

    EVENT_TYPE: typing.ClassVar[str] = "readers.created"
    type: typing.Literal["readers.created"] = "readers.created"
    _response_model: typing.ClassVar[typing.Type[pydantic.BaseModel]] = Reader


class ReaderDeletedEvent(FetchableEvent[Reader]):
    """Sent when a reader is unpaired from a merchant account and is no longer available through the Readers API."""

    EVENT_TYPE: typing.ClassVar[str] = "readers.deleted"
    type: typing.Literal["readers.deleted"] = "readers.deleted"
    _response_model: typing.ClassVar[typing.Type[pydantic.BaseModel]] = Reader


KnownEventNotification = typing.Union[
    MemberCreatedEvent,
    MemberDeletedEvent,
    MemberUpdatedEvent,
    ReaderCreatedEvent,
    ReaderDeletedEvent,
]


_EVENT_MODELS: typing.Dict[str, typing.Type[EventNotification]] = {
    "members.created": MemberCreatedEvent,
    "members.deleted": MemberDeletedEvent,
    "members.updated": MemberUpdatedEvent,
    "readers.created": ReaderCreatedEvent,
    "readers.deleted": ReaderDeletedEvent,
}


__all__ = [
    "AsyncEventCallback",
    "AsyncEventsHandler",
    "DEFAULT_TOLERANCE",
    "EventCallback",
    "EventError",
    "EventHandlerRegistrationError",
    "EventNotification",
    "EventObject",
    "EventObjectUrlError",
    "EventSignatureError",
    "EventSignatureExpiredError",
    "EventTimestampError",
    "EventsHandler",
    "FetchableEvent",
    "KnownEventNotification",
    "SIGNATURE_HEADER",
    "SIGNATURE_VERSION",
    "TIMESTAMP_HEADER",
    "UnknownEvent",
    "dangerously_parse_unverified_event_notification",
    "parse_event_notification",
    "verify_signature",
    "MemberCreatedEvent",
    "MemberDeletedEvent",
    "MemberUpdatedEvent",
    "ReaderCreatedEvent",
    "ReaderDeletedEvent",
]
