# Code generated by `py-sdk-gen`. DO NOT EDIT.
from __future__ import annotations

import builtins
import typing

import pydantic

from ._events import (
    SIGNATURE_HEADER,
    AsyncEventCallback,
    EventBody,
    EventCallback,
    EventCallbackError,
    EventError,
    EventHandlerRegistrationError,
    EventNotification,
    EventObject,
    EventObjectUrlError,
    EventPayloadError,
    EventSignatureError,
    EventSignatureExpiredError,
    EventTimestampError,
    FetchableEvent,
    UnknownEvent,
    _AsyncEventsHandler,
    _ErasedCallback,
    _SyncEventsHandler,
    verify_event_signature,
)
from .types import (
    Member,
    Reader,
)


class MemberCreatedEvent(FetchableEvent[Member]):
    """Sent when a member is created, invited, or accepts an invitation for a merchant account.

    The notification type is "members.created". Use fetch_object() with
    Sumup or await fetch_object_async() with AsyncSumup to retrieve the latest
    Member. The notification itself contains a resource reference.
    """

    EVENT_TYPE: typing.ClassVar[str] = "members.created"
    type: typing.Literal["members.created"] = "members.created"
    _object_type: typing.ClassVar[str] = "member"
    _response_model: typing.ClassVar[builtins.type[pydantic.BaseModel]] = Member


class MemberDeletedEvent(FetchableEvent[Member]):
    """Sent when a member is deleted from a merchant account.

    The notification type is "members.deleted". Use fetch_object() with
    Sumup or await fetch_object_async() with AsyncSumup to retrieve the latest
    Member. The notification itself contains a resource reference.
    """

    EVENT_TYPE: typing.ClassVar[str] = "members.deleted"
    type: typing.Literal["members.deleted"] = "members.deleted"
    _object_type: typing.ClassVar[str] = "member"
    _response_model: typing.ClassVar[builtins.type[pydantic.BaseModel]] = Member


class MemberUpdatedEvent(FetchableEvent[Member]):
    """Sent when a member is updated, disabled, rejected, or expires for a merchant account.

    The notification type is "members.updated". Use fetch_object() with
    Sumup or await fetch_object_async() with AsyncSumup to retrieve the latest
    Member. The notification itself contains a resource reference.
    """

    EVENT_TYPE: typing.ClassVar[str] = "members.updated"
    type: typing.Literal["members.updated"] = "members.updated"
    _object_type: typing.ClassVar[str] = "member"
    _response_model: typing.ClassVar[builtins.type[pydantic.BaseModel]] = Member


class ReaderCreatedEvent(FetchableEvent[Reader]):
    """Sent when a reader is paired to a merchant account and becomes available through the Readers API.

    The notification type is "readers.created". Use fetch_object() with
    Sumup or await fetch_object_async() with AsyncSumup to retrieve the latest
    Reader. The notification itself contains a resource reference.
    """

    EVENT_TYPE: typing.ClassVar[str] = "readers.created"
    type: typing.Literal["readers.created"] = "readers.created"
    _object_type: typing.ClassVar[str] = "reader"
    _response_model: typing.ClassVar[builtins.type[pydantic.BaseModel]] = Reader


class ReaderDeletedEvent(FetchableEvent[Reader]):
    """Sent when a reader is unpaired from a merchant account and is no longer available through the Readers API.

    The notification type is "readers.deleted". Use fetch_object() with
    Sumup or await fetch_object_async() with AsyncSumup to retrieve the latest
    Reader. The notification itself contains a resource reference.
    """

    EVENT_TYPE: typing.ClassVar[str] = "readers.deleted"
    type: typing.Literal["readers.deleted"] = "readers.deleted"
    _object_type: typing.ClassVar[str] = "reader"
    _response_model: typing.ClassVar[builtins.type[pydantic.BaseModel]] = Reader


KnownEventNotification = (
    MemberCreatedEvent
    | MemberDeletedEvent
    | MemberUpdatedEvent
    | ReaderCreatedEvent
    | ReaderDeletedEvent
)


_EVENT_MODELS: dict[str, type[EventNotification]] = {
    "members.created": MemberCreatedEvent,
    "members.deleted": MemberDeletedEvent,
    "members.updated": MemberUpdatedEvent,
    "readers.created": ReaderCreatedEvent,
    "readers.deleted": ReaderDeletedEvent,
}


_MemberCreatedEventCallback = typing.TypeVar(
    "_MemberCreatedEventCallback", bound=typing.Callable[[MemberCreatedEvent], None]
)
_AsyncMemberCreatedEventCallback = typing.TypeVar(
    "_AsyncMemberCreatedEventCallback",
    bound=typing.Callable[[MemberCreatedEvent], typing.Awaitable[None]],
)
_MemberDeletedEventCallback = typing.TypeVar(
    "_MemberDeletedEventCallback", bound=typing.Callable[[MemberDeletedEvent], None]
)
_AsyncMemberDeletedEventCallback = typing.TypeVar(
    "_AsyncMemberDeletedEventCallback",
    bound=typing.Callable[[MemberDeletedEvent], typing.Awaitable[None]],
)
_MemberUpdatedEventCallback = typing.TypeVar(
    "_MemberUpdatedEventCallback", bound=typing.Callable[[MemberUpdatedEvent], None]
)
_AsyncMemberUpdatedEventCallback = typing.TypeVar(
    "_AsyncMemberUpdatedEventCallback",
    bound=typing.Callable[[MemberUpdatedEvent], typing.Awaitable[None]],
)
_ReaderCreatedEventCallback = typing.TypeVar(
    "_ReaderCreatedEventCallback", bound=typing.Callable[[ReaderCreatedEvent], None]
)
_AsyncReaderCreatedEventCallback = typing.TypeVar(
    "_AsyncReaderCreatedEventCallback",
    bound=typing.Callable[[ReaderCreatedEvent], typing.Awaitable[None]],
)
_ReaderDeletedEventCallback = typing.TypeVar(
    "_ReaderDeletedEventCallback", bound=typing.Callable[[ReaderDeletedEvent], None]
)
_AsyncReaderDeletedEventCallback = typing.TypeVar(
    "_AsyncReaderDeletedEventCallback",
    bound=typing.Callable[[ReaderDeletedEvent], typing.Awaitable[None]],
)


class EventsHandler(_SyncEventsHandler):
    """Verify incoming events and dispatch them to typed synchronous callbacks.

    Create with client.events_handler(secret, fallback). Register callbacks once
    at startup using a decorator or a direct method call::

        @handler.on_reader_created
        def reader_created(event: ReaderCreatedEvent) -> None:
            reader = event.fetch_object()
            print(reader.id)

    Registration returns the original function, preserving its type and identity.
    Unknown event types and known types without a callback reach the fallback.
    Callbacks receive one event and must return None or raise an exception.

    Call handle(body, signature) with the raw request body and complete signature
    header. Send a successful HTTP response after handling completes. Deliveries
    may be repeated; make side effects idempotent and synchronize shared state if
    serving concurrent requests. The caller owns request-body limits.
    """

    def on_member_created(
        self, callback: _MemberCreatedEventCallback
    ) -> _MemberCreatedEventCallback:
        """Register a callback for members.created and return it unchanged.

        Use @handler.on_member_created or handler.on_member_created(callback).
        The callback receives one MemberCreatedEvent and returns None on success;
        raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("members.created", typing.cast(_ErasedCallback, callback))
        return callback

    def on_member_deleted(
        self, callback: _MemberDeletedEventCallback
    ) -> _MemberDeletedEventCallback:
        """Register a callback for members.deleted and return it unchanged.

        Use @handler.on_member_deleted or handler.on_member_deleted(callback).
        The callback receives one MemberDeletedEvent and returns None on success;
        raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("members.deleted", typing.cast(_ErasedCallback, callback))
        return callback

    def on_member_updated(
        self, callback: _MemberUpdatedEventCallback
    ) -> _MemberUpdatedEventCallback:
        """Register a callback for members.updated and return it unchanged.

        Use @handler.on_member_updated or handler.on_member_updated(callback).
        The callback receives one MemberUpdatedEvent and returns None on success;
        raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("members.updated", typing.cast(_ErasedCallback, callback))
        return callback

    def on_reader_created(
        self, callback: _ReaderCreatedEventCallback
    ) -> _ReaderCreatedEventCallback:
        """Register a callback for readers.created and return it unchanged.

        Use @handler.on_reader_created or handler.on_reader_created(callback).
        The callback receives one ReaderCreatedEvent and returns None on success;
        raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("readers.created", typing.cast(_ErasedCallback, callback))
        return callback

    def on_reader_deleted(
        self, callback: _ReaderDeletedEventCallback
    ) -> _ReaderDeletedEventCallback:
        """Register a callback for readers.deleted and return it unchanged.

        Use @handler.on_reader_deleted or handler.on_reader_deleted(callback).
        The callback receives one ReaderDeletedEvent and returns None on success;
        raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("readers.deleted", typing.cast(_ErasedCallback, callback))
        return callback


class AsyncEventsHandler(_AsyncEventsHandler):
    """Verify incoming events and dispatch them to typed asynchronous callbacks.

    Create with client.events_handler(secret, fallback) on an AsyncSumup client.
    Register async callbacks at startup using decorators or direct method calls::

        @handler.on_reader_created
        async def reader_created(event: ReaderCreatedEvent) -> None:
            reader = await event.fetch_object_async()
            print(reader.id)

    Registration returns the original function. Unknown and unregistered types
    reach the required async fallback. Await handle(body, signature) before
    acknowledging delivery; the handler awaits the selected callback. Parsing
    alone via parse() is synchronous and performs no network requests.

    Make side effects idempotent for repeat deliveries. Concurrent requests may
    run callbacks concurrently; synchronize shared state and configure body limits
    in your HTTP server.
    """

    def on_member_created(
        self, callback: _AsyncMemberCreatedEventCallback
    ) -> _AsyncMemberCreatedEventCallback:
        """Register an async callback for members.created and return it unchanged.

        Use @handler.on_member_created or handler.on_member_created(callback).
        The callback receives one MemberCreatedEvent and is awaited by handle().
        Return None on success or raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("members.created", typing.cast(_ErasedCallback, callback))
        return callback

    def on_member_deleted(
        self, callback: _AsyncMemberDeletedEventCallback
    ) -> _AsyncMemberDeletedEventCallback:
        """Register an async callback for members.deleted and return it unchanged.

        Use @handler.on_member_deleted or handler.on_member_deleted(callback).
        The callback receives one MemberDeletedEvent and is awaited by handle().
        Return None on success or raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("members.deleted", typing.cast(_ErasedCallback, callback))
        return callback

    def on_member_updated(
        self, callback: _AsyncMemberUpdatedEventCallback
    ) -> _AsyncMemberUpdatedEventCallback:
        """Register an async callback for members.updated and return it unchanged.

        Use @handler.on_member_updated or handler.on_member_updated(callback).
        The callback receives one MemberUpdatedEvent and is awaited by handle().
        Return None on success or raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("members.updated", typing.cast(_ErasedCallback, callback))
        return callback

    def on_reader_created(
        self, callback: _AsyncReaderCreatedEventCallback
    ) -> _AsyncReaderCreatedEventCallback:
        """Register an async callback for readers.created and return it unchanged.

        Use @handler.on_reader_created or handler.on_reader_created(callback).
        The callback receives one ReaderCreatedEvent and is awaited by handle().
        Return None on success or raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("readers.created", typing.cast(_ErasedCallback, callback))
        return callback

    def on_reader_deleted(
        self, callback: _AsyncReaderDeletedEventCallback
    ) -> _AsyncReaderDeletedEventCallback:
        """Register an async callback for readers.deleted and return it unchanged.

        Use @handler.on_reader_deleted or handler.on_reader_deleted(callback).
        The callback receives one ReaderDeletedEvent and is awaited by handle().
        Return None on success or raise an exception to signal processing failure.

        Raises:
            EventHandlerRegistrationError: The callback is not callable, or this
                event type already has a registered callback.
        """
        self._register("readers.deleted", typing.cast(_ErasedCallback, callback))
        return callback


__all__ = [
    "SIGNATURE_HEADER",
    "AsyncEventCallback",
    "AsyncEventsHandler",
    "EventBody",
    "EventCallback",
    "EventCallbackError",
    "EventError",
    "EventHandlerRegistrationError",
    "EventNotification",
    "EventObject",
    "EventObjectUrlError",
    "EventPayloadError",
    "EventSignatureError",
    "EventSignatureExpiredError",
    "EventTimestampError",
    "EventsHandler",
    "KnownEventNotification",
    "MemberCreatedEvent",
    "MemberDeletedEvent",
    "MemberUpdatedEvent",
    "ReaderCreatedEvent",
    "ReaderDeletedEvent",
    "UnknownEvent",
    "verify_event_signature",
]
