# Code generated by `py-sdk-gen`. DO NOT EDIT.
import datetime
import typing
import pydantic


class MembershipUserClassic(pydantic.BaseModel):
    """
            Classic identifiers of the user.
    Deprecated: this operation is deprecated
    """

    user_id: int
    """
	Format: int32
	"""


class MembershipUser(pydantic.BaseModel):
    """
    Information about the user associated with the membership.
    """

    email: str
    """
	End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. TheRP MUST NOT rely upon this value being unique, for unique identification use ID instead.
	"""

    id: str
    """
	Identifier for the End-User (also called Subject).
	"""

    mfa_on_login_enabled: bool
    """
	True if the user has enabled MFA on login.
	"""

    service_account_user: bool
    """
	True if the user is a service account.
	"""

    virtual_user: bool
    """
	True if the user is a virtual user (operator).
	"""

    classic: typing.Optional[MembershipUserClassic] = None
    """
	Classic identifiers of the user.
	Deprecated: this operation is deprecated
	"""

    disabled_at: typing.Optional[datetime.datetime] = None
    """
	Time when the user has been disabled. Applies only to virtual users (`virtual_user: true`).
	"""

    nickname: typing.Optional[str] = None
    """
	User's preferred name. Used for display purposes only.
	"""

    picture: typing.Optional[str] = None
    """
	URL of the End-User's profile picture. This URL refers to an image file (for example, a PNG, JPEG, or GIFimage file), rather than to a Web page containing an image.
	Format: uri
	"""


class Invite(pydantic.BaseModel):
    """
    Pending invitation for membership.
    """

    email: str
    """
	Email address of the invited user.
	Format: email
	"""

    expires_at: datetime.datetime


MembershipStatus = typing.Literal["accepted", "disabled", "expired", "pending", "unknown"]

Metadata = dict[typing.Any, typing.Any]
"""
Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, alwayssubmit whole metadata. Maximum of 64 parameters are allowed in the object.
Max properties: 64
"""

Attributes = dict[typing.Any, typing.Any]
"""
Object attributes that are modifiable only by SumUp applications.
"""


class Member(pydantic.BaseModel):
    """
    A member is user within specific resource identified by resource id, resource type, and associated roles.
    """

    created_at: datetime.datetime
    """
	The timestamp of when the member was created.
	"""

    id: str
    """
	ID of the member.
	"""

    permissions: list[str]
    """
	User's permissions.
	Deprecated: Permissions include only legacy permissions, please use roles instead. Member access is based on roles withina given resource and the permissions these roles grant.
	"""

    roles: list[str]
    """
	User's roles.
	"""

    status: MembershipStatus
    """
	The status of the membership.
	"""

    updated_at: datetime.datetime
    """
	The timestamp of when the member was last updated.
	"""

    attributes: typing.Optional[Attributes] = None
    """
	Object attributes that are modifiable only by SumUp applications.
	"""

    invite: typing.Optional[Invite] = None
    """
	Pending invitation for membership.
	"""

    metadata: typing.Optional[Metadata] = None
    """
	Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, alwayssubmit whole metadata. Maximum of 64 parameters are allowed in the object.
	Max properties: 64
	"""

    user: typing.Optional[MembershipUser] = None
    """
	Information about the user associated with the membership.
	"""


class Problem(pydantic.BaseModel):
    """
            A RFC 9457 problem details object.

    Additional properties specific to the problem type may be present.
    """

    type: str
    """
	A URI reference that identifies the problem type.
	Format: uri
	"""

    detail: typing.Optional[str] = None
    """
	A human-readable explanation specific to this occurrence of the problem.
	"""

    instance: typing.Optional[str] = None
    """
	A URI reference that identifies the specific occurrence of the problem.
	Format: uri
	"""

    status: typing.Optional[int] = None
    """
	The HTTP status code generated by the origin server for this occurrence of the problem.
	Min: 400
	Max: 600
	"""

    title: typing.Optional[str] = None
    """
	A short, human-readable summary of the problem type.
	"""
