# Code generated by `py-sdk-gen`. DO NOT EDIT.
import datetime
import typing
import pydantic

Metadata = dict[typing.Any, typing.Any]
"""
Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, alwayssubmit whole metadata. Maximum of 64 parameters are allowed in the object.
Max properties: 64
"""


class Role(pydantic.BaseModel):
    """
    A custom role that can be used to assign set of permissions to members.
    """

    created_at: datetime.datetime
    """
	The timestamp of when the role was created.
	"""

    id: str
    """
	Unique identifier of the role.
	"""

    is_predefined: bool
    """
	True if the role is provided by SumUp.
	"""

    name: str
    """
	User-defined name of the role.
	"""

    permissions: list[str]
    """
	List of permission granted by this role.
	Max items: 100
	"""

    updated_at: datetime.datetime
    """
	The timestamp of when the role was last updated.
	"""

    description: typing.Optional[str] = None
    """
	User-defined description of the role.
	"""

    metadata: typing.Optional[Metadata] = None
    """
	Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, alwayssubmit whole metadata. Maximum of 64 parameters are allowed in the object.
	Max properties: 64
	"""


class Problem(pydantic.BaseModel):
    """
            A RFC 9457 problem details object.

    Additional properties specific to the problem type may be present.
    """

    type: str
    """
	A URI reference that identifies the problem type.
	Format: uri
	"""

    detail: typing.Optional[str] = None
    """
	A human-readable explanation specific to this occurrence of the problem.
	"""

    instance: typing.Optional[str] = None
    """
	A URI reference that identifies the specific occurrence of the problem.
	Format: uri
	"""

    status: typing.Optional[int] = None
    """
	The HTTP status code generated by the origin server for this occurrence of the problem.
	Min: 400
	Max: 600
	"""

    title: typing.Optional[str] = None
    """
	A short, human-readable summary of the problem type.
	"""
