# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
Checkouts represent online payment sessions that you create before attempting to charge a payer. A checkout captures the payment intent, such as the amount, currency, merchant, and optional customer or redirect settings, and then moves through its lifecycle as you process it.

Use this tag to:
- create a checkout before collecting or confirming payment details
- process the checkout with a card, saved card, wallet, or supported alternative payment method
- retrieve or list checkouts to inspect their current state and associated payment attempts
- deactivate a checkout that should no longer be used

Typical workflow:
- create a checkout with the order amount, currency, and merchant information
- process the checkout through SumUp client tools such as the [Payment Widget and Swift Checkout SDK](https://developer.sumup.com/online-payments/checkouts)
- retrieve the checkout or use the Transactions endpoints to inspect the resulting payment record

Checkouts are used to initiate and orchestrate online payments. Transactions remain the authoritative record of the resulting payment outcome.
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import (
    AddressLegacy,
    Card,
    CardType,
    Checkout,
    CheckoutAccepted,
    CheckoutCreateRequest,
    CheckoutSuccess,
    Currency,
    DetailsError,
    EntryMode,
    Error,
    ErrorExtended,
    ErrorForbidden,
    HostedCheckout,
    MandatePayload,
    MandateResponse,
    PaymentType,
    PersonalDetails,
    Problem,
    ProcessCheckout,
    TransactionBase,
    TransactionCheckoutInfo,
)
from ..types import (
    AddressLegacyInput,
    CardInput,
    CardTypeInput,
    CheckoutCreateRequestInput,
    CurrencyInput,
    HostedCheckoutInput,
    MandatePayloadInput,
    PersonalDetailsInput,
    ProcessCheckoutInput,
)
import datetime
import httpx
import typing
import pydantic
import typing_extensions

CreateCheckoutBodyPurposeInput = typing.Union[
    typing.Literal["CHECKOUT", "SETUP_RECURRING_PAYMENT"], str
]


class CreateCheckoutBodyInput(typing_extensions.TypedDict, total=False):
    """
    Request body for creating a checkout before processing payment. Define the payment amount, currency, merchant,and optional customer or redirect behavior here.
    """

    amount: typing_extensions.Required[
        typing_extensions.Annotated[
            float,
            typing_extensions.Doc("Amount to be charged to the payer, expressed in major units."),
        ]
    ]
    checkout_reference: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Merchant-defined reference for the new checkout. It should be unique enough for you to identify the payment attemptin your own systems.\nMax length: 90"
            ),
        ]
    ]
    currency: typing_extensions.Required[
        typing_extensions.Annotated[
            CurrencyInput,
            typing_extensions.Doc(
                "Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supportedcurrency values are enumerated above."
            ),
        ]
    ]
    merchant_code: typing_extensions.Required[
        typing_extensions.Annotated[
            str, typing_extensions.Doc("Merchant account that should receive the payment.")
        ]
    ]
    customer_id: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Merchant-scoped customer identifier. Required when setting up recurring payments and useful when the checkoutshould be linked to a returning payer."
            ),
        ]
    ]
    description: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Short merchant-defined description shown in SumUp tools and reporting for easier identification of the checkout."
            ),
        ]
    ]
    hosted_checkout: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            HostedCheckoutInput,
            typing_extensions.Doc(
                "Hosted Checkout configuration. Enable it to receive a SumUp-hosted payment page URL in the checkout response."
            ),
        ]
    ]
    purpose: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CreateCheckoutBodyPurposeInput,
            typing_extensions.Doc(
                'Business purpose of the checkout. Use `CHECKOUT` for a standard payment and `SETUP_RECURRING_PAYMENT` whencollecting consent and payment details for future recurring charges.\nDefault: "CHECKOUT"'
            ),
        ]
    ]
    redirect_url: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "URL where the payer should be sent after a redirect-based payment or SCA flow completes. This is required for[APMs](https://developer.sumup.com/online-payments/apm/introduction) and recommended for card checkouts thatmay require [3DS](https://developer.sumup.com/online-payments/features/3ds). If it is omitted, the [Payment Widget](https://developer.sumup.com/online-payments/checkouts)can render the challenge in an iframe instead of using a full-page redirect."
            ),
        ]
    ]
    return_url: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Optional backend callback URL used by SumUp to notify your platform about processing updates for the checkout.\nFormat:uri"
            ),
        ]
    ]
    valid_until: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            datetime.datetime,
            typing_extensions.Doc(
                "Optional expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable.If omitted, the checkout does not have an explicit expiry time."
            ),
        ]
    ]


ProcessCheckoutBodyPaymentTypeInput = typing.Union[
    typing.Literal["apple_pay", "bancontact", "blik", "boleto", "card", "google_pay", "ideal"], str
]

ProcessCheckoutBodyGooglePayInput = typing.Mapping[str, object]
"""
Raw `PaymentData` object received from Google Pay. Send the Google Pay response payload as-is.
"""

ProcessCheckoutBodyApplePayInput = typing.Mapping[str, object]
"""
Raw payment token object received from Apple Pay. Send the Apple Pay response payload as-is.
"""


class ProcessCheckoutBodyInput(typing_extensions.TypedDict, total=False):
    """
    Request body for attempting payment on an existing checkout. The required companion fields depend on theselected `payment_type`, for example card details, saved-card data, or payer information required by aspecific payment method.
    """

    payment_type: typing_extensions.Required[
        typing_extensions.Annotated[
            ProcessCheckoutBodyPaymentTypeInput,
            typing_extensions.Doc(
                "Payment method used for this processing attempt. It determines which additional request fields are required."
            ),
        ]
    ]
    apple_pay: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            ProcessCheckoutBodyApplePayInput,
            typing_extensions.Doc(
                "Raw payment token object received from Apple Pay. Send the Apple Pay response payload as-is."
            ),
        ]
    ]
    card: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            CardInput,
            typing_extensions.Doc(
                "__Required when payment type is `card`.__ Details of the payment card."
            ),
        ]
    ]
    customer_id: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Customer identifier associated with the saved payment instrument. Required when `token` is provided."
            ),
        ]
    ]
    google_pay: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            ProcessCheckoutBodyGooglePayInput,
            typing_extensions.Doc(
                "Raw `PaymentData` object received from Google Pay. Send the Google Pay response payload as-is."
            ),
        ]
    ]
    installments: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            int,
            typing_extensions.Doc(
                "Number of installments for deferred payments. Available only to merchant users in Brazil.\nMin: 1\nMax: 12"
            ),
        ]
    ]
    mandate: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            MandatePayloadInput,
            typing_extensions.Doc(
                "Mandate details used when a checkout should create a reusable card token for future recurring or merchant-initiated payments."
            ),
        ]
    ]
    personal_details: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            PersonalDetailsInput, typing_extensions.Doc("Personal details for the customer.")
        ]
    ]
    token: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "Saved-card token to use instead of raw card details when processing with a previously stored payment instrument."
            ),
        ]
    ]


class CreateApplePaySessionBodyInput(typing_extensions.TypedDict, total=False):
    """
    CreateApplePaySessionBody is a schema definition.
    """

    context: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc(
                "the context to create this apple pay session.\nFormat: hostname"
            ),
        ]
    ]
    target: typing_extensions.Required[
        typing_extensions.Annotated[
            str,
            typing_extensions.Doc("The target url to create this apple pay session.\nFormat: uri"),
        ]
    ]


class GetPaymentMethods200ResponseAvailablePaymentMethod(pydantic.BaseModel):
    """
    GetPaymentMethods200ResponseAvailablePaymentMethod is a schema definition.
    """

    id: str
    """
	The ID of the payment method.
	"""


class GetPaymentMethods200Response(pydantic.BaseModel):
    """
    GetPaymentMethods200Response is a schema definition.
    """

    available_payment_methods: typing.Optional[
        list[GetPaymentMethods200ResponseAvailablePaymentMethod]
    ] = None


ListCheckouts200Response = list[CheckoutSuccess]
"""
ListCheckouts200Response is a schema definition.
"""

ProcessCheckoutResponse = typing.Union[CheckoutSuccess, CheckoutAccepted]

CreateApplePaySession200Response = dict[str, object]
"""
CreateApplePaySession200Response is a schema definition.
"""


class CheckoutsResource(Resource):
    """API resource for the Checkouts endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def list_available_payment_methods(
        self,
        merchant_code: str,
        *,
        amount: typing.Union[float, NotGivenType] = NOT_GIVEN,
        currency: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> GetPaymentMethods200Response:
        """
        Get available payment methods

        Get payment methods available for the given merchant to use with a checkout.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(amount, NotGivenType) and amount is not None:
            query_data["amount"] = amount
        if not isinstance(currency, NotGivenType) and currency is not None:
            query_data["currency"] = currency

        resp = self._client.get(
            f"/v0.1/merchants/{merchant_code}/payment-methods",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(GetPaymentMethods200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def create(
        self,
        *,
        checkout_reference: str,
        amount: float,
        currency: CurrencyInput,
        merchant_code: str,
        description: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        return_url: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        customer_id: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        purpose: typing.Union[CreateCheckoutBodyPurposeInput, None, NotGivenType] = NOT_GIVEN,
        valid_until: typing.Union[datetime.datetime, None, NotGivenType] = NOT_GIVEN,
        redirect_url: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        hosted_checkout: typing.Union[HostedCheckoutInput, None, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Checkout:
        """
        Create a checkout

        Creates a new payment checkout resource. The unique `checkout_reference` created by this request, is used for furthermanipulation of the checkout.

        For 3DS checkouts, add the `redirect_url` parameter to your request body schema.
        To use the [Hosted Checkout](https://developer.sumup.com/online-payments/checkouts/hosted-checkout/) page, setthe `hosted_checkout.enabled` to `true`.

        Follow by processing a checkout to charge the provided payment instrument.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["checkout_reference"] = checkout_reference
        body_data["amount"] = amount
        body_data["currency"] = currency
        body_data["merchant_code"] = merchant_code
        if not isinstance(description, NotGivenType):
            body_data["description"] = description
        if not isinstance(return_url, NotGivenType):
            body_data["return_url"] = return_url
        if not isinstance(customer_id, NotGivenType):
            body_data["customer_id"] = customer_id
        if not isinstance(purpose, NotGivenType):
            body_data["purpose"] = purpose
        if not isinstance(valid_until, NotGivenType):
            body_data["valid_until"] = valid_until
        if not isinstance(redirect_url, NotGivenType):
            body_data["redirect_url"] = redirect_url
        if not isinstance(hosted_checkout, NotGivenType):
            body_data["hosted_checkout"] = hosted_checkout

        resp = self._client.post(
            f"/v0.1/checkouts",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(Checkout).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError("The request body is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request isn't sufficiently authorized to create a checkout.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 409:
            raise APIError(
                "A checkout already exists for the provided unique parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def list(
        self,
        *,
        checkout_reference: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListCheckouts200Response:
        """
        List checkouts

        Lists created checkout resources according to the applied `checkout_reference`.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(checkout_reference, NotGivenType) and checkout_reference is not None:
            query_data["checkout_reference"] = checkout_reference

        resp = self._client.get(
            f"/v0.1/checkouts",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListCheckouts200Response).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def get(self, id: str, headers: typing.Optional[HeaderTypes] = None) -> CheckoutSuccess:
        """
        Retrieve a checkout

        Retrieves an identified checkout resource. Use this request after processing a checkout to confirm its status and informthe end user respectively.
        """
        resp = self._client.get(
            f"/v0.1/checkouts/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(CheckoutSuccess).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def process(
        self,
        id: str,
        *,
        payment_type: ProcessCheckoutBodyPaymentTypeInput,
        installments: typing.Union[int, None, NotGivenType] = NOT_GIVEN,
        mandate: typing.Union[MandatePayloadInput, None, NotGivenType] = NOT_GIVEN,
        card: typing.Union[CardInput, None, NotGivenType] = NOT_GIVEN,
        google_pay: typing.Union[ProcessCheckoutBodyGooglePayInput, None, NotGivenType] = NOT_GIVEN,
        apple_pay: typing.Union[ProcessCheckoutBodyApplePayInput, None, NotGivenType] = NOT_GIVEN,
        token: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        customer_id: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        personal_details: typing.Union[PersonalDetailsInput, None, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ProcessCheckoutResponse:
        """
        Process a checkout

        Processing a checkout will attempt to charge the provided payment instrument for the amount of the specified checkout resourceinitiated in the `Create a checkout` endpoint.

        Follow this request with `Retrieve a checkout` to confirm its status.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["payment_type"] = payment_type
        if not isinstance(installments, NotGivenType):
            body_data["installments"] = installments
        if not isinstance(mandate, NotGivenType):
            body_data["mandate"] = mandate
        if not isinstance(card, NotGivenType):
            body_data["card"] = card
        if not isinstance(google_pay, NotGivenType):
            body_data["google_pay"] = google_pay
        if not isinstance(apple_pay, NotGivenType):
            body_data["apple_pay"] = apple_pay
        if not isinstance(token, NotGivenType):
            body_data["token"] = token
        if not isinstance(customer_id, NotGivenType):
            body_data["customer_id"] = customer_id
        if not isinstance(personal_details, NotGivenType):
            body_data["personal_details"] = personal_details

        resp = self._client.put(
            f"/v0.1/checkouts/{id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(CheckoutSuccess).validate_python(resp.json())
        elif resp.status_code == 202:
            return pydantic.TypeAdapter(CheckoutAccepted).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request body is invalid for processing the checkout.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The request conflicts with the current state of the resource.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def deactivate(self, id: str, headers: typing.Optional[HeaderTypes] = None) -> Checkout:
        """
        Deactivate a checkout

        Deactivates an identified checkout resource. If the checkout has already been processed it can not be deactivated.
        """
        resp = self._client.delete(
            f"/v0.1/checkouts/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Checkout).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The request conflicts with the current state of the resource.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def create_apple_pay_session(
        self, id: str, *, context: str, target: str, headers: typing.Optional[HeaderTypes] = None
    ) -> CreateApplePaySession200Response:
        """
        Create an Apple Pay session

        Creates an Apple Pay merchant session for the specified checkout.

        Use this endpoint after the customer selects Apple Pay and before calling
        `ApplePaySession.completeMerchantValidation(...)` in the browser.
        SumUp validates the merchant session request and returns the Apple Pay
        session object that your frontend should pass to Apple's JavaScript API.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["context"] = context
        body_data["target"] = target

        resp = self._client.put(
            f"/v0.2/checkouts/{id}/apple-pay-session",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(CreateApplePaySession200Response).validate_python(
                resp.json()
            )
        elif resp.status_code == 400:
            raise APIError("Bad Request", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncCheckoutsResource(AsyncResource):
    """Async API resource for the Checkouts endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def list_available_payment_methods(
        self,
        merchant_code: str,
        *,
        amount: typing.Union[float, NotGivenType] = NOT_GIVEN,
        currency: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> GetPaymentMethods200Response:
        """
        Get available payment methods

        Get payment methods available for the given merchant to use with a checkout.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(amount, NotGivenType) and amount is not None:
            query_data["amount"] = amount
        if not isinstance(currency, NotGivenType) and currency is not None:
            query_data["currency"] = currency

        resp = await self._client.get(
            f"/v0.1/merchants/{merchant_code}/payment-methods",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(GetPaymentMethods200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def create(
        self,
        *,
        checkout_reference: str,
        amount: float,
        currency: CurrencyInput,
        merchant_code: str,
        description: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        return_url: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        customer_id: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        purpose: typing.Union[CreateCheckoutBodyPurposeInput, None, NotGivenType] = NOT_GIVEN,
        valid_until: typing.Union[datetime.datetime, None, NotGivenType] = NOT_GIVEN,
        redirect_url: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        hosted_checkout: typing.Union[HostedCheckoutInput, None, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Checkout:
        """
        Create a checkout

        Creates a new payment checkout resource. The unique `checkout_reference` created by this request, is used for furthermanipulation of the checkout.

        For 3DS checkouts, add the `redirect_url` parameter to your request body schema.
        To use the [Hosted Checkout](https://developer.sumup.com/online-payments/checkouts/hosted-checkout/) page, setthe `hosted_checkout.enabled` to `true`.

        Follow by processing a checkout to charge the provided payment instrument.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["checkout_reference"] = checkout_reference
        body_data["amount"] = amount
        body_data["currency"] = currency
        body_data["merchant_code"] = merchant_code
        if not isinstance(description, NotGivenType):
            body_data["description"] = description
        if not isinstance(return_url, NotGivenType):
            body_data["return_url"] = return_url
        if not isinstance(customer_id, NotGivenType):
            body_data["customer_id"] = customer_id
        if not isinstance(purpose, NotGivenType):
            body_data["purpose"] = purpose
        if not isinstance(valid_until, NotGivenType):
            body_data["valid_until"] = valid_until
        if not isinstance(redirect_url, NotGivenType):
            body_data["redirect_url"] = redirect_url
        if not isinstance(hosted_checkout, NotGivenType):
            body_data["hosted_checkout"] = hosted_checkout

        resp = await self._client.post(
            f"/v0.1/checkouts",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 201:
            return pydantic.TypeAdapter(Checkout).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError("The request body is invalid.", status=resp.status_code, body=resp.text)
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 403:
            raise APIError(
                "The request isn't sufficiently authorized to create a checkout.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 409:
            raise APIError(
                "A checkout already exists for the provided unique parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def list(
        self,
        *,
        checkout_reference: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListCheckouts200Response:
        """
        List checkouts

        Lists created checkout resources according to the applied `checkout_reference`.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(checkout_reference, NotGivenType) and checkout_reference is not None:
            query_data["checkout_reference"] = checkout_reference

        resp = await self._client.get(
            f"/v0.1/checkouts",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListCheckouts200Response).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def get(self, id: str, headers: typing.Optional[HeaderTypes] = None) -> CheckoutSuccess:
        """
        Retrieve a checkout

        Retrieves an identified checkout resource. Use this request after processing a checkout to confirm its status and informthe end user respectively.
        """
        resp = await self._client.get(
            f"/v0.1/checkouts/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(CheckoutSuccess).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def process(
        self,
        id: str,
        *,
        payment_type: ProcessCheckoutBodyPaymentTypeInput,
        installments: typing.Union[int, None, NotGivenType] = NOT_GIVEN,
        mandate: typing.Union[MandatePayloadInput, None, NotGivenType] = NOT_GIVEN,
        card: typing.Union[CardInput, None, NotGivenType] = NOT_GIVEN,
        google_pay: typing.Union[ProcessCheckoutBodyGooglePayInput, None, NotGivenType] = NOT_GIVEN,
        apple_pay: typing.Union[ProcessCheckoutBodyApplePayInput, None, NotGivenType] = NOT_GIVEN,
        token: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        customer_id: typing.Union[str, None, NotGivenType] = NOT_GIVEN,
        personal_details: typing.Union[PersonalDetailsInput, None, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ProcessCheckoutResponse:
        """
        Process a checkout

        Processing a checkout will attempt to charge the provided payment instrument for the amount of the specified checkout resourceinitiated in the `Create a checkout` endpoint.

        Follow this request with `Retrieve a checkout` to confirm its status.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["payment_type"] = payment_type
        if not isinstance(installments, NotGivenType):
            body_data["installments"] = installments
        if not isinstance(mandate, NotGivenType):
            body_data["mandate"] = mandate
        if not isinstance(card, NotGivenType):
            body_data["card"] = card
        if not isinstance(google_pay, NotGivenType):
            body_data["google_pay"] = google_pay
        if not isinstance(apple_pay, NotGivenType):
            body_data["apple_pay"] = apple_pay
        if not isinstance(token, NotGivenType):
            body_data["token"] = token
        if not isinstance(customer_id, NotGivenType):
            body_data["customer_id"] = customer_id
        if not isinstance(personal_details, NotGivenType):
            body_data["personal_details"] = personal_details

        resp = await self._client.put(
            f"/v0.1/checkouts/{id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(CheckoutSuccess).validate_python(resp.json())
        elif resp.status_code == 202:
            return pydantic.TypeAdapter(CheckoutAccepted).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request body is invalid for processing the checkout.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The request conflicts with the current state of the resource.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def deactivate(self, id: str, headers: typing.Optional[HeaderTypes] = None) -> Checkout:
        """
        Deactivate a checkout

        Deactivates an identified checkout resource. If the checkout has already been processed it can not be deactivated.
        """
        resp = await self._client.delete(
            f"/v0.1/checkouts/{id}",
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Checkout).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The request conflicts with the current state of the resource.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def create_apple_pay_session(
        self, id: str, *, context: str, target: str, headers: typing.Optional[HeaderTypes] = None
    ) -> CreateApplePaySession200Response:
        """
        Create an Apple Pay session

        Creates an Apple Pay merchant session for the specified checkout.

        Use this endpoint after the customer selects Apple Pay and before calling
        `ApplePaySession.completeMerchantValidation(...)` in the browser.
        SumUp validates the merchant session request and returns the Apple Pay
        session object that your frontend should pass to Apple's JavaScript API.
        """
        body_data: dict[str, typing.Any] = {}
        body_data["context"] = context
        body_data["target"] = target

        resp = await self._client.put(
            f"/v0.2/checkouts/{id}/apple-pay-session",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(CreateApplePaySession200Response).validate_python(
                resp.json()
            )
        elif resp.status_code == 400:
            raise APIError("Bad Request", status=resp.status_code, body=resp.text)
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
