# Code generated by `py-sdk-gen`. DO NOT EDIT.
"""
Transactions represent completed or attempted payment operations processed for a merchant account. A transaction contains the core payment result, such as the amount, currency, payment method, creation time, and current high-level status.

In addition to the main payment outcome, a transaction can contain related events that describe what happened after the original payment attempt. These events provide visibility into the financial lifecycle of the transaction, for example:
- `PAYOUT`: the payment being prepared for payout or included in a payout to the merchant
- `REFUND`: money returned to the payer
- `CHARGE_BACK`: money reversed after the original payment
- `PAYOUT_DEDUCTION`: an amount deducted from a payout to cover a refund or chargeback

From an integrator's perspective, transactions are the authoritative record of payment outcomes. Use this tag to:
- list transactions for reporting, reconciliation, and customer support workflows
- retrieve a single transaction when you need the latest payment details
- inspect `simple_status` for the current merchant-facing outcome of the payment
- inspect `events` or `transaction_events` when you need refund, payout, or chargeback history

Typical workflow:
- create and process payments through the Checkouts endpoints
- use the Transactions endpoints to read the resulting payment records
- use the returned statuses and events to update your own order, accounting, or support systems
"""

from __future__ import annotations
from .._service import Resource, AsyncResource, HeaderTypes
from .._exceptions import APIError
from ..types import (
    EntryMode,
    PaymentType,
    TransactionFull,
    TransactionHistory,
    TransactionsHistoryLink,
)
import datetime
import httpx
import typing
import pydantic
import typing_extensions


class RefundTransactionBody(pydantic.BaseModel):
    """
    Optional amount for partial refunds of transactions.
    """

    amount: typing.Optional[float] = None
    """
	Amount to be refunded. Eligible amount can't exceed the amount of the transaction and varies based on countryand currency. If you do not specify a value, the system performs a full refund of the transaction.
	"""


class GetTransactionV21Params(pydantic.BaseModel):
    """
    GetTransactionV21Params: query parameters for GetTransactionV2.1
    """

    client_transaction_id: typing.Optional[str] = None

    foreign_transaction_id: typing.Optional[str] = None

    id: typing.Optional[str] = None

    transaction_code: typing.Optional[str] = None


class GetTransactionParams(pydantic.BaseModel):
    """
    GetTransactionParams: query parameters for GetTransaction
    """

    id: typing.Optional[str] = None

    transaction_code: typing.Optional[str] = None


ListTransactionsV21ParamsOrder = typing.Union[typing.Literal["ascending", "descending"], str]

ListTransactionsV21ParamsStatuse = typing.Union[
    typing.Literal["CANCELLED", "CHARGE_BACK", "FAILED", "REFUNDED", "SUCCESSFUL"], str
]

ListTransactionsV21ParamsType = typing.Union[
    typing.Literal["CHARGE_BACK", "PAYMENT", "REFUND"], str
]


class ListTransactionsV21Params(pydantic.BaseModel):
    """
    ListTransactionsV21Params: query parameters for ListTransactionsV2.1
    """

    changes_since: typing.Optional[datetime.datetime] = None

    entry_modes: typing.Optional[list[EntryMode]] = pydantic.Field(
        default=None,
        serialization_alias="entry_modes[]",
        validation_alias=pydantic.AliasChoices("entry_modes[]", "entry_modes"),
    )

    limit: typing.Optional[int] = None

    newest_ref: typing.Optional[str] = None

    newest_time: typing.Optional[datetime.datetime] = None

    oldest_ref: typing.Optional[str] = None

    oldest_time: typing.Optional[datetime.datetime] = None

    order: typing.Optional[ListTransactionsV21ParamsOrder] = None

    payment_types: typing.Optional[list[PaymentType]] = None

    statuses: typing.Optional[list[ListTransactionsV21ParamsStatuse]] = pydantic.Field(
        default=None,
        serialization_alias="statuses[]",
        validation_alias=pydantic.AliasChoices("statuses[]", "statuses"),
    )

    transaction_code: typing.Optional[str] = None

    types: typing.Optional[list[ListTransactionsV21ParamsType]] = None

    users: typing.Optional[list[str]] = None


ListTransactionsParamsOrder = typing.Union[typing.Literal["ascending", "descending"], str]

ListTransactionsParamsStatuse = typing.Union[
    typing.Literal["CANCELLED", "CHARGE_BACK", "FAILED", "REFUNDED", "SUCCESSFUL"], str
]

ListTransactionsParamsType = typing.Union[typing.Literal["CHARGE_BACK", "PAYMENT", "REFUND"], str]


class ListTransactionsParams(pydantic.BaseModel):
    """
    ListTransactionsParams: query parameters for ListTransactions
    """

    changes_since: typing.Optional[datetime.datetime] = None

    limit: typing.Optional[int] = None

    newest_ref: typing.Optional[str] = None

    newest_time: typing.Optional[datetime.datetime] = None

    oldest_ref: typing.Optional[str] = None

    oldest_time: typing.Optional[datetime.datetime] = None

    order: typing.Optional[ListTransactionsParamsOrder] = None

    payment_types: typing.Optional[list[PaymentType]] = None

    statuses: typing.Optional[list[ListTransactionsParamsStatuse]] = pydantic.Field(
        default=None,
        serialization_alias="statuses[]",
        validation_alias=pydantic.AliasChoices("statuses[]", "statuses"),
    )

    transaction_code: typing.Optional[str] = None

    types: typing.Optional[list[ListTransactionsParamsType]] = None

    users: typing.Optional[list[str]] = None


class ListTransactionsV21200Response(pydantic.BaseModel):
    """
    ListTransactionsV21200Response is a schema definition.
    """

    items: typing.Optional[list[TransactionHistory]] = None

    links: typing.Optional[list[TransactionsHistoryLink]] = None


class ListTransactions200Response(pydantic.BaseModel):
    """
    ListTransactions200Response is a schema definition.
    """

    items: typing.Optional[list[TransactionHistory]] = None

    links: typing.Optional[list[TransactionsHistoryLink]] = None


class TransactionsResource(Resource):
    """API resource for the Transactions endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def refund(
        self, txn_id: str, body: RefundTransactionBody, headers: typing.Optional[HeaderTypes] = None
    ):
        """
        Refund a transaction

        Refunds an identified transaction either in full or partially.
        """
        resp = self._client.post(
            f"/v0.1/me/refund/{txn_id}",
            json=body.model_dump(exclude_unset=True),
            headers=headers,
        )
        if resp.status_code == 204:
            return
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The transaction cannot be refunded due to business constraints.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    def get(
        self,
        merchant_code: str,
        params: typing.Optional[GetTransactionV21Params] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        resp = self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    def get_deprecated(
        self,
        params: typing.Optional[GetTransactionParams] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        resp = self._client.get(
            "/v0.1/me/transactions",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    def list(
        self,
        merchant_code: str,
        params: typing.Optional[ListTransactionsV21Params] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactionsV21200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        resp = self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions/history",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactionsV21200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    def list_deprecated(
        self,
        params: typing.Optional[ListTransactionsParams] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactions200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        resp = self._client.get(
            "/v0.1/me/transactions/history",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactions200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)


class AsyncTransactionsResource(AsyncResource):
    """Async API resource for the Transactions endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def refund(
        self, txn_id: str, body: RefundTransactionBody, headers: typing.Optional[HeaderTypes] = None
    ):
        """
        Refund a transaction

        Refunds an identified transaction either in full or partially.
        """
        resp = await self._client.post(
            f"/v0.1/me/refund/{txn_id}",
            json=body.model_dump(exclude_unset=True),
            headers=headers,
        )
        if resp.status_code == 204:
            return
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The transaction cannot be refunded due to business constraints.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    async def get(
        self,
        merchant_code: str,
        params: typing.Optional[GetTransactionV21Params] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        resp = await self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    async def get_deprecated(
        self,
        params: typing.Optional[GetTransactionParams] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        resp = await self._client.get(
            "/v0.1/me/transactions",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    async def list(
        self,
        merchant_code: str,
        params: typing.Optional[ListTransactionsV21Params] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactionsV21200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        resp = await self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions/history",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactionsV21200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    async def list_deprecated(
        self,
        params: typing.Optional[ListTransactionsParams] = None,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactions200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        resp = await self._client.get(
            "/v0.1/me/transactions/history",
            params=params.model_dump(by_alias=True, exclude_none=True) if params else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactions200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError("Unexpected response", status=resp.status_code, body=resp.text)
