# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
Transactions represent completed or attempted payment operations processed for a merchant account. A transaction contains the core payment result, such as the amount, currency, payment method, creation time, and current high-level status.

In addition to the main payment outcome, a transaction can contain related events that describe what happened after the original payment attempt. These events provide visibility into the financial lifecycle of the transaction, for example:
- `PAYOUT`: the payment being prepared for payout or included in a payout to the merchant
- `REFUND`: money returned to the payer
- `CHARGE_BACK`: money reversed after the original payment
- `PAYOUT_DEDUCTION`: an amount deducted from a payout to cover a refund or chargeback

From an integrator's perspective, transactions are the authoritative record of payment outcomes. Use this tag to:
- list transactions for reporting, reconciliation, and customer support workflows
- retrieve a single transaction when you need the latest payment details
- inspect `simple_status` for the current merchant-facing outcome of the payment
- inspect `events` or `transaction_events` when you need refund, payout, or chargeback history

Typical workflow:
- create and process payments through the Checkouts endpoints
- use the Transactions endpoints to read the resulting payment records
- use the returned statuses and events to update your own order, accounting, or support systems
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import (
    CardResponse,
    CardType,
    Currency,
    Device,
    ElvCardAccount,
    EntryMode,
    Error,
    Event,
    EventId,
    EventStatus,
    EventType,
    HorizontalAccuracy,
    Lat,
    Link,
    Lon,
    PaymentType,
    Problem,
    Product,
    TransactionBase,
    TransactionCheckoutInfo,
    TransactionEvent,
    TransactionFull,
    TransactionHistory,
    TransactionId,
    TransactionMixinHistory,
    TransactionsHistoryLink,
)
from ..types import EntryModeInput, PaymentTypeInput
import datetime
import httpx
import typing
import pydantic
import typing_extensions


class RefundTransactionBodyInput(typing_extensions.TypedDict, total=False):
    """
    Optional amount for partial refunds of transactions.
    """

    amount: typing_extensions.NotRequired[
        typing_extensions.Annotated[
            float,
            typing_extensions.Doc(
                "Amount to be refunded. Eligible amount can't exceed the amount of the transaction and varies based on countryand currency. If you do not specify a value, the system performs a full refund of the transaction."
            ),
        ]
    ]


ListTransactionsV21ParamsOrderInput = typing.Union[typing.Literal["ascending", "descending"], str]

ListTransactionsV21ParamsStatuseInput = typing.Union[
    typing.Literal["CANCELLED", "CHARGE_BACK", "FAILED", "REFUNDED", "SUCCESSFUL"], str
]

ListTransactionsV21ParamsTypeInput = typing.Union[
    typing.Literal["CHARGE_BACK", "PAYMENT", "REFUND"], str
]

ListTransactionsParamsOrderInput = typing.Union[typing.Literal["ascending", "descending"], str]

ListTransactionsParamsStatuseInput = typing.Union[
    typing.Literal["CANCELLED", "CHARGE_BACK", "FAILED", "REFUNDED", "SUCCESSFUL"], str
]

ListTransactionsParamsTypeInput = typing.Union[
    typing.Literal["CHARGE_BACK", "PAYMENT", "REFUND"], str
]


class ListTransactionsV21200Response(pydantic.BaseModel):
    """
    ListTransactionsV21200Response is a schema definition.
    """

    items: typing.Optional[list[TransactionHistory]] = None

    links: typing.Optional[list[TransactionsHistoryLink]] = None


class ListTransactions200Response(pydantic.BaseModel):
    """
    ListTransactions200Response is a schema definition.
    """

    items: typing.Optional[list[TransactionHistory]] = None

    links: typing.Optional[list[TransactionsHistoryLink]] = None


class TransactionsResource(Resource):
    """API resource for the Transactions endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def refund(
        self,
        txn_id: str,
        *,
        amount: typing.Union[float, None, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ):
        """
        Refund a transaction

        Refunds an identified transaction either in full or partially.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(amount, NotGivenType):
            body_data["amount"] = amount

        resp = self._client.post(
            f"/v0.1/me/refund/{txn_id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 204:
            return
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The transaction cannot be refunded due to business constraints.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def get(
        self,
        merchant_code: str,
        *,
        id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        foreign_transaction_id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        client_transaction_id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(id, NotGivenType) and id is not None:
            query_data["id"] = id
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code
        if (
            not isinstance(foreign_transaction_id, NotGivenType)
            and foreign_transaction_id is not None
        ):
            query_data["foreign_transaction_id"] = foreign_transaction_id
        if (
            not isinstance(client_transaction_id, NotGivenType)
            and client_transaction_id is not None
        ):
            query_data["client_transaction_id"] = client_transaction_id

        resp = self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    def get_deprecated(
        self,
        *,
        id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(id, NotGivenType) and id is not None:
            query_data["id"] = id
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code

        resp = self._client.get(
            f"/v0.1/me/transactions",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    def list(
        self,
        merchant_code: str,
        *,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        order: typing.Union[ListTransactionsV21ParamsOrderInput, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        users: typing.Union[typing.Sequence[str], NotGivenType] = NOT_GIVEN,
        statuses: typing.Union[
            typing.Sequence[ListTransactionsV21ParamsStatuseInput], NotGivenType
        ] = NOT_GIVEN,
        payment_types: typing.Union[typing.Sequence[PaymentTypeInput], NotGivenType] = NOT_GIVEN,
        entry_modes: typing.Union[typing.Sequence[EntryModeInput], NotGivenType] = NOT_GIVEN,
        types: typing.Union[
            typing.Sequence[ListTransactionsV21ParamsTypeInput], NotGivenType
        ] = NOT_GIVEN,
        changes_since: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        oldest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        oldest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactionsV21200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code
        if not isinstance(order, NotGivenType) and order is not None:
            query_data["order"] = order
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(users, NotGivenType) and users is not None:
            query_data["users"] = list(users)
        if not isinstance(statuses, NotGivenType) and statuses is not None:
            query_data["statuses[]"] = list(statuses)
        if not isinstance(payment_types, NotGivenType) and payment_types is not None:
            query_data["payment_types"] = list(payment_types)
        if not isinstance(entry_modes, NotGivenType) and entry_modes is not None:
            query_data["entry_modes[]"] = list(entry_modes)
        if not isinstance(types, NotGivenType) and types is not None:
            query_data["types"] = list(types)
        if not isinstance(changes_since, NotGivenType) and changes_since is not None:
            query_data["changes_since"] = changes_since
        if not isinstance(newest_time, NotGivenType) and newest_time is not None:
            query_data["newest_time"] = newest_time
        if not isinstance(newest_ref, NotGivenType) and newest_ref is not None:
            query_data["newest_ref"] = newest_ref
        if not isinstance(oldest_time, NotGivenType) and oldest_time is not None:
            query_data["oldest_time"] = oldest_time
        if not isinstance(oldest_ref, NotGivenType) and oldest_ref is not None:
            query_data["oldest_ref"] = oldest_ref

        resp = self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions/history",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactionsV21200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    def list_deprecated(
        self,
        *,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        order: typing.Union[ListTransactionsParamsOrderInput, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        users: typing.Union[typing.Sequence[str], NotGivenType] = NOT_GIVEN,
        statuses: typing.Union[
            typing.Sequence[ListTransactionsParamsStatuseInput], NotGivenType
        ] = NOT_GIVEN,
        payment_types: typing.Union[typing.Sequence[PaymentTypeInput], NotGivenType] = NOT_GIVEN,
        types: typing.Union[
            typing.Sequence[ListTransactionsParamsTypeInput], NotGivenType
        ] = NOT_GIVEN,
        changes_since: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        oldest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        oldest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactions200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code
        if not isinstance(order, NotGivenType) and order is not None:
            query_data["order"] = order
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(users, NotGivenType) and users is not None:
            query_data["users"] = list(users)
        if not isinstance(statuses, NotGivenType) and statuses is not None:
            query_data["statuses[]"] = list(statuses)
        if not isinstance(payment_types, NotGivenType) and payment_types is not None:
            query_data["payment_types"] = list(payment_types)
        if not isinstance(types, NotGivenType) and types is not None:
            query_data["types"] = list(types)
        if not isinstance(changes_since, NotGivenType) and changes_since is not None:
            query_data["changes_since"] = changes_since
        if not isinstance(newest_time, NotGivenType) and newest_time is not None:
            query_data["newest_time"] = newest_time
        if not isinstance(newest_ref, NotGivenType) and newest_ref is not None:
            query_data["newest_ref"] = newest_ref
        if not isinstance(oldest_time, NotGivenType) and oldest_time is not None:
            query_data["oldest_time"] = oldest_time
        if not isinstance(oldest_ref, NotGivenType) and oldest_ref is not None:
            query_data["oldest_ref"] = oldest_ref

        resp = self._client.get(
            f"/v0.1/me/transactions/history",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactions200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncTransactionsResource(AsyncResource):
    """Async API resource for the Transactions endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def refund(
        self,
        txn_id: str,
        *,
        amount: typing.Union[float, None, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ):
        """
        Refund a transaction

        Refunds an identified transaction either in full or partially.
        """
        body_data: dict[str, typing.Any] = {}
        if not isinstance(amount, NotGivenType):
            body_data["amount"] = amount

        resp = await self._client.post(
            f"/v0.1/me/refund/{txn_id}",
            json=serialize_request_data(body_data),
            headers=headers,
        )
        if resp.status_code == 204:
            return
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 409:
            raise APIError(
                "The transaction cannot be refunded due to business constraints.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def get(
        self,
        merchant_code: str,
        *,
        id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        foreign_transaction_id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        client_transaction_id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(id, NotGivenType) and id is not None:
            query_data["id"] = id
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code
        if (
            not isinstance(foreign_transaction_id, NotGivenType)
            and foreign_transaction_id is not None
        ):
            query_data["foreign_transaction_id"] = foreign_transaction_id
        if (
            not isinstance(client_transaction_id, NotGivenType)
            and client_transaction_id is not None
        ):
            query_data["client_transaction_id"] = client_transaction_id

        resp = await self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    async def get_deprecated(
        self,
        *,
        id: typing.Union[str, NotGivenType] = NOT_GIVEN,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> TransactionFull:
        """
        Retrieve a transaction

        Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and*one* of following parameters is required:
        - `id`
        - `transaction_code`
        - `foreign_transaction_id`
        - `client_transaction_id`
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(id, NotGivenType) and id is not None:
            query_data["id"] = id
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code

        resp = await self._client.get(
            f"/v0.1/me/transactions",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(TransactionFull).validate_python(resp.json())
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested resource does not exist.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    async def list(
        self,
        merchant_code: str,
        *,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        order: typing.Union[ListTransactionsV21ParamsOrderInput, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        users: typing.Union[typing.Sequence[str], NotGivenType] = NOT_GIVEN,
        statuses: typing.Union[
            typing.Sequence[ListTransactionsV21ParamsStatuseInput], NotGivenType
        ] = NOT_GIVEN,
        payment_types: typing.Union[typing.Sequence[PaymentTypeInput], NotGivenType] = NOT_GIVEN,
        entry_modes: typing.Union[typing.Sequence[EntryModeInput], NotGivenType] = NOT_GIVEN,
        types: typing.Union[
            typing.Sequence[ListTransactionsV21ParamsTypeInput], NotGivenType
        ] = NOT_GIVEN,
        changes_since: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        oldest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        oldest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactionsV21200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code
        if not isinstance(order, NotGivenType) and order is not None:
            query_data["order"] = order
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(users, NotGivenType) and users is not None:
            query_data["users"] = list(users)
        if not isinstance(statuses, NotGivenType) and statuses is not None:
            query_data["statuses[]"] = list(statuses)
        if not isinstance(payment_types, NotGivenType) and payment_types is not None:
            query_data["payment_types"] = list(payment_types)
        if not isinstance(entry_modes, NotGivenType) and entry_modes is not None:
            query_data["entry_modes[]"] = list(entry_modes)
        if not isinstance(types, NotGivenType) and types is not None:
            query_data["types"] = list(types)
        if not isinstance(changes_since, NotGivenType) and changes_since is not None:
            query_data["changes_since"] = changes_since
        if not isinstance(newest_time, NotGivenType) and newest_time is not None:
            query_data["newest_time"] = newest_time
        if not isinstance(newest_ref, NotGivenType) and newest_ref is not None:
            query_data["newest_ref"] = newest_ref
        if not isinstance(oldest_time, NotGivenType) and oldest_time is not None:
            query_data["oldest_time"] = oldest_time
        if not isinstance(oldest_ref, NotGivenType) and oldest_ref is not None:
            query_data["oldest_ref"] = oldest_ref

        resp = await self._client.get(
            f"/v2.1/merchants/{merchant_code}/transactions/history",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactionsV21200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)

    @typing_extensions.deprecated("This method is deprecated")
    async def list_deprecated(
        self,
        *,
        transaction_code: typing.Union[str, NotGivenType] = NOT_GIVEN,
        order: typing.Union[ListTransactionsParamsOrderInput, NotGivenType] = NOT_GIVEN,
        limit: typing.Union[int, NotGivenType] = NOT_GIVEN,
        users: typing.Union[typing.Sequence[str], NotGivenType] = NOT_GIVEN,
        statuses: typing.Union[
            typing.Sequence[ListTransactionsParamsStatuseInput], NotGivenType
        ] = NOT_GIVEN,
        payment_types: typing.Union[typing.Sequence[PaymentTypeInput], NotGivenType] = NOT_GIVEN,
        types: typing.Union[
            typing.Sequence[ListTransactionsParamsTypeInput], NotGivenType
        ] = NOT_GIVEN,
        changes_since: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        newest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        oldest_time: typing.Union[datetime.datetime, NotGivenType] = NOT_GIVEN,
        oldest_ref: typing.Union[str, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> ListTransactions200Response:
        """
        List transactions

        Lists detailed history of all transactions associated with the merchant profile.
        """
        query_data: dict[str, typing.Any] = {}
        if not isinstance(transaction_code, NotGivenType) and transaction_code is not None:
            query_data["transaction_code"] = transaction_code
        if not isinstance(order, NotGivenType) and order is not None:
            query_data["order"] = order
        if not isinstance(limit, NotGivenType) and limit is not None:
            query_data["limit"] = limit
        if not isinstance(users, NotGivenType) and users is not None:
            query_data["users"] = list(users)
        if not isinstance(statuses, NotGivenType) and statuses is not None:
            query_data["statuses[]"] = list(statuses)
        if not isinstance(payment_types, NotGivenType) and payment_types is not None:
            query_data["payment_types"] = list(payment_types)
        if not isinstance(types, NotGivenType) and types is not None:
            query_data["types"] = list(types)
        if not isinstance(changes_since, NotGivenType) and changes_since is not None:
            query_data["changes_since"] = changes_since
        if not isinstance(newest_time, NotGivenType) and newest_time is not None:
            query_data["newest_time"] = newest_time
        if not isinstance(newest_ref, NotGivenType) and newest_ref is not None:
            query_data["newest_ref"] = newest_ref
        if not isinstance(oldest_time, NotGivenType) and oldest_time is not None:
            query_data["oldest_time"] = oldest_time
        if not isinstance(oldest_ref, NotGivenType) and oldest_ref is not None:
            query_data["oldest_ref"] = oldest_ref

        resp = await self._client.get(
            f"/v0.1/me/transactions/history",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(ListTransactions200Response).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted query parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
