# Code generated by `py-sdk-gen`. DO NOT EDIT.
# ruff: noqa: F401, F541
"""
The Receipts model obtains receipt-like details for specific transactions.
"""

from __future__ import annotations
from .._service import (
    Resource,
    AsyncResource,
    HeaderTypes,
    NotGivenType,
    NOT_GIVEN,
    serialize_query_params,
    serialize_request_data,
)
from .._exceptions import APIError
from ..types import (
    Error,
    EventId,
    EventStatus,
    EventType,
    Problem,
    Receipt,
    ReceiptCard,
    ReceiptEvent,
    ReceiptMerchantData,
    ReceiptReader,
    ReceiptTransaction,
    TransactionId,
)
from ..types import (
    ErrorInput,
    EventIdInput,
    EventStatusInput,
    EventTypeInput,
    ProblemInput,
    ReceiptInput,
    ReceiptCardInput,
    ReceiptEventInput,
    ReceiptMerchantDataInput,
    ReceiptReaderInput,
    ReceiptTransactionInput,
    TransactionIdInput,
)
import datetime
import httpx
import typing
import pydantic
import typing_extensions


class ReceiptsResource(Resource):
    """API resource for the Receipts endpoints."""

    def __init__(self, client: httpx.Client) -> None:
        super().__init__(client)

    def get(
        self,
        id: str,
        *,
        mid: str,
        tx_event_id: typing.Union[int, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Receipt:
        """
        Retrieve receipt details

        Retrieves receipt specific data for a transaction.
        """
        query_data: dict[str, typing.Any] = {}
        query_data["mid"] = mid
        if not isinstance(tx_event_id, NotGivenType) and tx_event_id is not None:
            query_data["tx_event_id"] = tx_event_id

        resp = self._client.get(
            f"/v1.1/receipts/{id}",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Receipt).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested transaction event does not exist for the provided transaction.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)


class AsyncReceiptsResource(AsyncResource):
    """Async API resource for the Receipts endpoints."""

    def __init__(self, client: httpx.AsyncClient) -> None:
        super().__init__(client)

    async def get(
        self,
        id: str,
        *,
        mid: str,
        tx_event_id: typing.Union[int, NotGivenType] = NOT_GIVEN,
        headers: typing.Optional[HeaderTypes] = None,
    ) -> Receipt:
        """
        Retrieve receipt details

        Retrieves receipt specific data for a transaction.
        """
        query_data: dict[str, typing.Any] = {}
        query_data["mid"] = mid
        if not isinstance(tx_event_id, NotGivenType) and tx_event_id is not None:
            query_data["tx_event_id"] = tx_event_id

        resp = await self._client.get(
            f"/v1.1/receipts/{id}",
            params=serialize_query_params(query_data) if query_data else None,
            headers=headers,
        )
        if resp.status_code == 200:
            return pydantic.TypeAdapter(Receipt).validate_python(resp.json())
        elif resp.status_code == 400:
            raise APIError(
                "The request is invalid for the submitted parameters.",
                status=resp.status_code,
                body=resp.text,
            )
        elif resp.status_code == 401:
            raise APIError(
                "The request is not authorized.", status=resp.status_code, body=resp.text
            )
        elif resp.status_code == 404:
            raise APIError(
                "The requested transaction event does not exist for the provided transaction.",
                status=resp.status_code,
                body=resp.text,
            )
        else:
            raise APIError(f"Unexpected response", status=resp.status_code, body=resp.text)
